acls:
    marello_packing_slip_create:
        type: entity
        class: Marello\Bundle\PackingBundle\Entity\PackingSlip
        permission: CREATE

    marello_packing_slip_view:
        type: entity
        class: Marello\Bundle\PackingBundle\Entity\PackingSlip
        permission: VIEW

    marello_packing_slip_update:
        type: entity
        class: Marello\Bundle\PackingBundle\Entity\PackingSlip
        permission: EDIT
