system_configuration:
    groups:
        notification_packingslip:
            title: marello.notification.system_configuration.groups.notification_packingslip.label
            priority: 50

    fields:
        marello_packing.send_packing_slip_template:
            data_type: string
            type: 'Marello\Bundle\NotificationBundle\Form\Type\EmailTemplateSelectType'
            options:
                label: marello.notification.config.fields.packing.send_packing_slip.label
                required: false
                entityName: Marello\Bundle\PackingBundle\Entity\PackingSlip
                placeholder: marello.notification.config.fields.email_template.placeholder

    tree:
        system_configuration:
            marello:
                children:
                    notification:
                        children:
                            notification_configuration:
                                children:
                                    notification_packingslip:
                                        children:
                                            - marello_packing.send_packing_slip_template
        organization_configuration:
            marello:
                children:
                    notification:
                        children:
                            notification_configuration:
                                children:
                                    notification_packingslip:
                                        children:
                                            - marello_packing.send_packing_slip_template
        saleschannel_configuration:
            marello:
                children:
                    notification:
                        children:
                            notification_configuration:
                                children:
                                    notification_packingslip:
                                        children:
                                            - marello_packing.send_packing_slip_template