acls:
    marello_inventory_warehouse_update:
        type:       entity
        class:      Marello\Bundle\InventoryBundle\Entity\Warehouse
        permission: EDIT

    marello_inventory_product_stock_modify:
        type:       entity
        class:      Marello\Bundle\InventoryBundle\Entity\InventoryItem
        permission: EDIT

    marello_inventory_product_stock_view:
        type:       entity
        class:      Marello\Bundle\InventoryBundle\Entity\InventoryItem
        permission: VIEW

    marello_inventory_inventory_recalculate_update:
        type:       entity
        class:      Marello\Bundle\InventoryBundle\Entity\BalancedInventoryLevel
        permission: EDIT