navigation:
    menu_config:
        items:
            warehouses:
                label: marello.inventory.warehouse.entity_label
                route: marello_inventory_warehouse_updatedefault
                extras:
                    routes: ['marello_inventory_warehouse_*']
            inventory_management:
                label: marello.inventory.management.menu.label
                uri:  '#'
                extras:
                    position: 20
            inventory:
                label: marello.inventory.management.menu.label
                route: marello_inventory_inventory_index
                extras:
                    routes: ['marello_inventory_inventory_*', 'marello_inventory_inventorylevel_*']
                    position: 20

            balanced_inventory:
                label: marello.inventory.management.menu.balanced_inventory.label
                route: marello_inventory_balancedinventorylevel_index
                extras:
                    routes: ['marello_inventory_balancedinventorylevel_index*']
                    position: 30
            allocations:
                label: marello.inventory.allocation.entity_plural_label
                route: marello_inventory_allocation_index
                extras:
                    routes: ['marello_inventory_allocation_index*']
                    position: 25
        tree:
            application_menu:
                children:
                    system_tab:
                        children:
                            warehouses: ~
                    products_tab:
                        children:
                            inventory_management:
                                children:
                                    inventory: ~
                                    balanced_inventory: ~
                    sales_tab:
                        children:
                            allocations: ~

    titles:
        marello_inventory_warehouse_updatedefault: 'Default Warehouse - Update'
        marello_inventory_inventory_index: 'marello.inventory.label'
        marello_inventory_inventory_update: 'Update Inventory'
        marello_inventory_inventorylevel_index: 'marello.inventory.management.menu.inventory_level_log.label'
        marello_inventory_balancedinventorylevel_index: 'marello.inventory.management.menu.balanced_inventory.label'
        marello_inventory_inventorylevel_manage_batches: 'marello.inventory.inventorybatch.entity_plural_label'
        marello_inventory_allocation_index: 'marello.inventory.allocation.entity_plural_label'
        marello_inventory_allocation_view: 'marello.inventory.allocation.page_title.view'
        marello_inventory_reshipment_create: 'marello.inventory.reshipment.label'
        marello_inventory_expected_inventory_item_view: 'marello.inventory.inventorylevel.expected_inventory.label'
