marello_inventory_inventory:
    resource: "@MarelloInventoryBundle/Controller/InventoryItemController.php"
    type:     annotation
    prefix:   /marello/inventory/inventory-item

marello_inventory_inventorylevel:
    resource: "@MarelloInventoryBundle/Controller/InventoryLevelController.php"
    type:     annotation
    prefix:   /marello/inventory/inventory-level

marello_inventory_balancedinventorylevel:
    resource: "@MarelloInventoryBundle/Controller/BalancedInventoryLevelController.php"
    type:     annotation
    prefix:   /marello/inventory/balanced-inventory-level

marello_inventory_warehouse:
    resource: "@MarelloInventoryBundle/Controller/WarehouseController.php"
    type:     annotation
    prefix:   /marello/inventory/warehouse

marello_inventory_allocation:
    resource: "@MarelloInventoryBundle/Controller/AllocationController.php"
    type:     annotation
    prefix:   /marello/inventory/allocation

marello_inventory_reshipment:
    resource: "@MarelloInventoryBundle/Controller/ReshipmentController.php"
    type:     annotation
    prefix:   /marello/reshipment

marello_inventory_expected_inventory_item:
    resource: "@MarelloInventoryBundle/Controller/ExpectedInventoryItemController.php"
    type:     annotation
    prefix:   /marello/inventory/expected-inventory-item
