system_configuration:
    groups:
        inventory:
            title: marello.inventory.system_configuration.groups.inventory.title
        inventory_balancing:
            title: marello.inventory.system_configuration.groups.inventory.balacing.title
            icon: fa-cubes
        inventory_balancing_general:
            title: marello.inventory.system_configuration.groups.inventory.balacing.general.label
        inventory_balancing_strategy:
            title: marello.inventory.system_configuration.groups.inventory.balacing.strategy.label
        inventory_on_demand:
            title: marello.inventory.system_configuration.groups.inventory.on_demand.title
            icon: fa-cog
        inventory_on_demand_general:
            title: marello.inventory.system_configuration.groups.inventory.on_demand.general.label
        inventory_allocation:
            title: marello.inventory.system_configuration.groups.inventory.allocation.title
            icon: fa-cog
        inventory_allocation_general:
            title: marello.inventory.system_configuration.groups.inventory.allocation.general.label

    fields:
        marello_inventory.balance_threshold_percentage:
            data_type: percent
            type: Oro\Bundle\FormBundle\Form\Type\OroPercentType
            options:
                label: marello.inventory.system_configuration.fields.balance_threshold_percentage.label
                tooltip: marello.inventory.system_configuration.fields.tooltip.balance_threshold_percentage
                required: true
                constraints:
                    - NotBlank: ~

        marello_inventory.balancing_strategy:
            data_type: string
            type: Marello\Bundle\InventoryBundle\Form\Type\BalancerStrategyChoiceType
            options:
                label: marello.inventory.system_configuration.fields.balancing_strategy.label
                required: true
                constraints:
                    - NotBlank: ~

        marello_inventory.inventory_allocation_priority:
            data_type: string
            type: Marello\Bundle\InventoryBundle\Form\Type\InventoryAllocationPriorityChoiceType
            options:
                label: marello.inventory.system_configuration.fields.inventory_allocation_priority.label
                tooltip: marello.inventory.system_configuration.fields.tooltip.inventory_allocation_priority
                required: true
                constraints:
                    - NotBlank: ~

    tree:
        system_configuration:
            marello:
                children:
                    inventory:
                        children:
                            inventory_balancing:
                                children:
                                    inventory_balancing_general:
                                        children:
                                            - marello_inventory.balance_threshold_percentage
                                    inventory_balancing_strategy:
                                        children:
                                            - marello_inventory.balancing_strategy
                            inventory_allocation:
                                children:
                                    inventory_allocation_general:
                                        children:
                                            - marello_inventory.inventory_allocation_priority
