acls:
    marello_order_create:
        type: entity
        class: Marello\Bundle\OrderBundle\Entity\Order
        permission: CREATE

    marello_order_view:
        type: entity
        class: Marello\Bundle\OrderBundle\Entity\Order
        permission: VIEW

    marello_order_update:
        type: entity
        class: Marello\Bundle\OrderBundle\Entity\Order
        permission: EDIT
