api:
    entity_aliases:
        Marello\Bundle\OrderBundle\Entity\Order:
            alias: marelloorder
            plural_alias: marelloorders

        Marello\Bundle\OrderBundle\Entity\OrderItem:
            alias: marelloorderitem
            plural_alias: marelloorderitems

    entities:
        Marello\Bundle\OrderBundle\Entity\Order:
            documentation_resource: '@MarelloOrderBundle/Resources/doc/api/order.md'
            fields:
                createdAt:
                    exclude: true
                updatedAt:
                    exclude: true
            filters:
                exclusion_policy: all
                fields:
                    orderNumber:
                        data_type: string
                        allow_array: true
                        property_path: orderNumber
                        description: 'Filter by order number'
                    orderReference:
                        data_type: string
                        allow_array: true
                        property_path: orderReference
                        description: 'Filter by order reference'
                        operators: ['=', '!=', '*', '!*', '~', '!~', '^', '!^', '$', '!$']
                    salesChannel:
                        data_type: string
                        allow_array: true
                        property_path: salesChannel.code
                        description: 'Filter by SalesChannel'
                        operators: ['=', '!=', '*', '!*', '~', '!~', '^', '!^', '$', '!$']
                    createdAt:
                        exclude: true
                    updatedAt:
                        exclude: true
            sorters:
                fields:
                    purchaseDate: ~
                    orderReference: ~
            actions:
                update: false
                delete: false
                delete_list: false
                update_relationship: false
                delete_relationship: false

        Marello\Bundle\OrderBundle\Entity\OrderItem:
            form_options:
                validation_groups: ['api']
            fields:
                createdAt:
                    exclude: true
                updatedAt:
                    exclude: true
                variantHash:
                    exclude: true
            filters:
                exclusion_policy: all
                fields:
                    orders:
                        data_type: integer
                        allow_array: true
                        property_path: order
                        description: 'Filter by order ID'
                    status_id:
                        data_type: string
                        allow_array: true
                        property_path: status_id
                        description: 'Filter by status'
            actions:
                delete: false
                delete_list: false
                update_relationship: false
                delete_relationship: false