oro_entity:
    entity_aliases:
        Marello\Bundle\OrderBundle\Entity\Customer:
            alias: marellocustomer
            plural_alias: marellocustomers

        Marello\Bundle\OrderBundle\Entity\Order:
            alias: marelloorder
            plural_alias: marelloorders

        Marello\Bundle\OrderBundle\Entity\OrderItem:
            alias: marelloorderitem
            plural_alias: marelloorderitems
