search:
    Marello\Bundle\OrderBundle\Entity\Order:
        alias:                          marello_order
        label:                          marello.order.entity_plural_label
        route:
            name:                       marello_order_order_view
            parameters:
                id:                     id
        search_template:                '@MarelloOrder/Order/searchResult.html.twig'
        fields:
            -
                name:                   orderNumber
                target_type:            text
                target_fields:          [orderNumber]
            -
                name:                   customer
                relation_type:          many-to-one
                relation_fields:
                    -
                        name:           email
                        target_type:    text
                        target_fields:  [email]
                    -
                        name:           firstName
                        target_type:    text
                        target_fields:  [firstName]
                    -
                        name:           lastName
                        target_type:    text
                        target_fields:  [lastName]
