acls:
    marello_purchase_order_create:
        type:       entity
        class:      MarelloPurchaseOrderBundle:PurchaseOrder
        permission: CREATE

    marello_purchase_order_view:
        type:       entity
        class:      MarelloPurchaseOrderBundle:PurchaseOrder
        permission: VIEW

    marello_purchase_order_update:
        type: entity
        class: MarelloPurchaseOrderBundle:PurchaseOrder
        permission: EDIT