search:
    Marello\Bundle\PurchaseOrderBundle\Entity\PurchaseOrder:
        alias:                          marello_purchaseorder
        label:                          marello.purchaseorder.entity_plural_label
        route:
            name:                       marello_purchaseorder_purchaseorder_view
            parameters:
                id:                     id
        search_template:                '@MarelloPurchaseOrder/PurchaseOrder/searchResult.html.twig'
        fields:
            -
                name:                   purchaseOrderNumber
                target_type:            text
                target_fields:          [purchaseOrderNumber]
            -
                name:                   supplier
                relation_type:          many-to-one
                relation_fields:
                    -
                        name:           email
                        target_type:    text
                        target_fields:  [email]
                    -
                        name:           name
                        target_type:    text
                        target_fields:  [name]
