workflows:
    marello_purchase_order_workflow:
        entity: Marello\Bundle\PurchaseOrderBundle\Entity\PurchaseOrder
        entity_attribute: po
        start_step: not_sent

        defaults:
            active: true

        attributes:
            received_items:
                type: entity
                options:
                    class: Marello\Bundle\PurchaseOrderBundle\Entity\PurchaseOrder
            pickup_location:
                type: string
        steps:
            not_sent:
                allowed_transitions:
                    - send
            pending:
                allowed_transitions:
                    - partially_receive
                    - cancel_purchase_order
            partially_received:
                allowed_transitions:
                    - partially_receive
                    - complete_purchase_order
            complete_purchase_order:
                is_final: true
            cancelled_purchase_order:
                allowed_transitions:
                    - send
        transitions:
            send:
                step_to: pending
                is_start: true
                transition_definition: send_definition
            partially_receive:
                step_to: partially_received
                transition_definition: partially_receive_definition
                display_type: page
                page_template: '@OroWorkflow/Workflow/transitionForm.html.twig'
                form_options:
                    attribute_fields:
                        pickup_location:
                            form_type: Symfony\Component\Form\Extension\Core\Type\TextType
                            options:
                                required: false
                        received_items:
                            form_type: Marello\Bundle\PurchaseOrderBundle\Form\Type\PartialReceiveType
                            options:
                                required: true
                                data: $po
            complete_purchase_order:
                step_to: complete_purchase_order
                transition_definition: complete_purchase_order_definition
            cancel_purchase_order:
                step_to: cancelled_purchase_order
                transition_definition: cancel_purchase_order_definition
        transition_definitions:
            send_definition:
                actions:
                    - '@marello_purchase_order_send':
                        entity: $po
                        recipient: $po.supplier
                        template: marello_purchase_order_supplier
            partially_receive_definition:
                actions:
                    - '@marello_receive_purchase_order':
                        entity: $received_items
                        is_partial: true
                        pickup_location: $pickup_location
                    - '@marello_purchase_order_transit_complete_action':
                        transitionName: 'complete_purchase_order'
                        entity: $received_items
            complete_purchase_order_definition:
                actions:
                    - '@marello_receive_purchase_order':
                        entity: $po
                    - '@marello_purchase_order_transit_complete_action':
                        entity: $po
                    - '@extendable':
                       events: [extendable_action.purchase_order_completed]
            cancel_purchase_order_definition: ~