datagrids:
    marello-replenishment-orders-grid:
        source:
            type: orm
            query:
                select:
                    - ro
                    - o.label as originLabel
                    - d.label as destinationLabel
                    - c.percentage as percentage
                from:
                    - { table: MarelloEnterpriseReplenishmentBundle:ReplenishmentOrder, alias: ro }
                join:
                    inner:
                        - { join: ro.origin, alias: o }
                        - { join: ro.destination, alias: d }
                    left:
                        - { join: ro.replOrderConfig, alias: c }
        columns:
            replOrderNumber:
                label: marelloenterprise.replenishment.replenishmentorder.repl_order_number.label
                frontend_type: string
            originLabel:
                label: marelloenterprise.replenishment.replenishmentorder.origin.label
                frontend_type: string
            destinationLabel:
                label: marelloenterprise.replenishment.replenishmentorder.destination.label
                frontend_type: string
            executionDateTime:
                label: marelloenterprise.replenishment.replenishmentorder.execution_date_time.label
                frontend_type: datetime
            percentage:
                label: marelloenterprise.replenishment.replenishmentorderconfig.percentage.label
                type: twig
                frontend_type: html
                template: '@MarelloEnterpriseReplenishment/ReplenishmentOrder/Datagrid/Property/percentage.html.twig'
            description:
                label: marelloenterprise.replenishment.replenishmentorder.description.label
                frontend_type: string
        sorters:
            columns:
                replOrderNumber:
                    data_name: ro.replOrderNumber
                originLabel:
                    data_name: o.label
                destinationLabel:
                    data_name: d.label
                percentage:
                    data_name: c.percentage
            default:
                replOrderNumber: 'DESC'
        properties:
            view_link:
                type:   url
                route:  marelloenterprise_replenishmentorder_view
                params:
                    id: id
        actions:
            view:
                type:           navigate
                label:          oro.grid.action.view
                link:           view_link
                icon:           eye
                acl_recource:   marelloenterprise_replenishmentorder_view
                rowAction:      true

    marello-replenishment-order-items-grid:
        source:
            type: orm
            query:
                select:
                    - roi
                from:
                    - { table: MarelloEnterpriseReplenishmentBundle:ReplenishmentOrderItem, alias: roi }
                where:
                    and:
                        - roi.order = :order_id
            bind_parameters:
                order_id: replOrderId
        columns:
            productSku:
                label: marelloenterprise.replenishment.replenishmentorderitem.product_sku.label
                frontend_type: string
            productName:
                label: marelloenterprise.replenishment.replenishmentorderitem.product_name.label
                frontend_type: string
            inventoryQty:
                label: marelloenterprise.replenishment.replenishmentorderitem.inventory_qty.label
                frontend_type: integer
            totalInventoryQty:
                label: marelloenterprise.replenishment.replenishmentorderitem.total_inventory_qty.label
                frontend_type: integer
            allQuantity:
                label: marelloenterprise.replenishment.replenishmentorderitem.all.label
                frontend_type: boolean
            inventoryBatches:
                label: marelloenterprise.replenishment.replenishmentorderitem.inventory_batches.label
                type: twig
                frontend_type: html
                template: '@MarelloEnterpriseReplenishment/ReplenishmentOrder/Datagrid/Property/inventoryBatches.html.twig'
            note:
                label: marelloenterprise.replenishment.replenishmentorderitem.note.label
                frontend_type: string

    marello-replenishment-products-candidates:
        source:
            type: orm
            query:
                select:
                    - p
                    - p.id
                    - p.sku
                    - p.denormalizedDefaultName as productName
                    - s.label as status
                    - >
                      (CASE WHEN p.id IN (:data_in) AND p.id NOT IN (:data_not_in)
                        THEN true ELSE false
                      END) as hasProduct
                from:
                    - { table: MarelloProductBundle:Product, alias: p }
                join:
                    left:
                        - { join: p.status, alias: s }
#                        - { join: p.categories, alias: cat }
                groupBy: p.id, s.label
        columns:
            hasProduct:
                label:              marello.purchaseorder.has_item.label
                editable:           true
                frontend_type:      boolean
            image:
                label:            marello.product.image.label
                type:             twig
                frontend_type:    html
                template:         '@MarelloProduct/Product/Datagrid/Property/image.html.twig'
            sku:
                label:              marello.product.sku.label
                frontend_type:      string
            productName:
                label:              marello.product.name.label
                frontend_type:      string
                data_name:          productName
            manufacturingCode:
                label:              marello.product.manufacturing_code.label
                frontend_type:      string
            status:
                label:              marello.product.status.label
                frontend_type:      string
#            categories:
#                label:              marello.product.categories.label
#                type:               twig
#                frontend_type:      html
#                template:           '@MarelloProduct/Product/Datagrid/Property/categories.html.twig'
            createdAt:
                label:              oro.ui.created_at
                frontend_type:      datetime
        sorters:
            columns:
                hasProduct:             { data_name: hasProduct }
                sku:                    { data_name: p.sku }
                productName:            { data_name: p.denormalizedDefaultName }
                manufacturingCode:      { data_name: p.manufacturingCode }
                status:                 { data_name: s.label }
#                categories:             { data_name: categoriesCount }
                createdAt:              { data_name: p.createdAt }
            default:
                hasProduct: 'DESC'
        filters:
            columns:
                image:
                    type:             boolean
                    data_name:        hasImage
                sku:
                    type:             string
                    data_name:        p.sku
                productName:
                    type:             string
                    data_name:        productName
                status:
                    type: entity
                    data_name: s
                    options:
                        field_options:
                            class: Marello\Bundle\ProductBundle\Entity\ProductStatus
                manufacturingCode:
                    data_name:          p.manufacturingCode
                    type:               string
        properties:
            id: ~
            view_link:
                type: url
                route: marello_product_view
                params:
                    - id
        options:
            entityHint: p
            rowSelection:
                dataField: id
                columnName: hasProduct
                selectors:
                    included: '#appendProducts'
                    excluded: '#removeProducts'
            requireJSModules:
                - marelloenterprisereplenishment/js/datagrid/marello-replenishment-products-candidates-builder