marelloenterprise_replenishment_order_config:
    resource: "@MarelloEnterpriseReplenishmentBundle/Controller/ReplenishmentOrderConfigController.php"
    type:     annotation
    prefix:   /marello/replenishment-order-config

marelloenterprise_replenishment_order:
    resource: "@MarelloEnterpriseReplenishmentBundle/Controller/ReplenishmentOrderController.php"
    type:     annotation
    prefix:   /marello/replenishment-order

marelloenterprise_replenishment_order_config_ajax:
    resource: "@MarelloEnterpriseReplenishmentBundle/Controller/ReplenishmentOrderConfigAjaxController.php"
    type:     annotation
    prefix:   /marello/replenishment-order-config
