services:
    marello_ups.validator.remove_used_shipping_service:
        class: 'Marello\Bundle\UPSBundle\Validator\Constraints\RemoveUsedShippingServiceValidator'
        arguments:
            - "@marello_ups.method.factory.method"
            - "@marello_shipping.method_validator.main"
        tags:
            - { name: validator.constraint_validator, alias: marello_ups_remove_used_shipping_service_validator }

    marello_ups.validator.country_shipping_services_validator:
        class: 'Marello\Bundle\UPSBundle\Validator\Constraints\CountryShippingServicesValidator'
        tags:
            - { name: validator.constraint_validator, alias: marello_ups_country_shipping_services_validator }
