workflows:
    marello_order_b2c_workflow_1:
        label:        'Order B2C Workflow #1'
        entity:       Marello\Bundle\OrderBundle\Entity\Order
        entity_attribute: order
        start_step:   pending
        attributes:
            payment_reference:
                label: 'Payment Reference'
                type: string
            payment_details:
                label: 'Payment Details'
                type: string
            invoiced_at:
                label: 'Invoiced At'
                type: object
                options:
                    class: \DateTime
            shipping_reference:
                label: 'Shipping Reference'
                type: string
            track_and_trace_number:
                label: 'Track & Trace Number'
                type: string
            shipped_at:
                label: 'Shipped At'
                type: object
                options:
                    class: \DateTime
            note:
                label: 'Note'
                type: string
        steps:
            pending:
                label:  Pending Order
                allowed_transitions:
                    - payment_reminder
                    - invoice
                    - hold_pending
                    - cancel
            cancelled:
                label:  Cancelled
                allowed_transitions: []
            pending_on_hold:
                label:  On Hold
                allowed_transitions:
                    - un_hold_pending
            invoice_on_hold:
                label:  On Hold
                allowed_transitions:
                    - un_hold_invoice
            invoice:
                label:  Order Payed
                allowed_transitions:
                    - hold_invoice
                    - credit
                    - prepare_shipping
            credit:
                label:  Closed
                allowed_transitions: []
            pick_and_pack:
                label: Pick and Pack
                allowed_transitions:
                    - ship
            shipped:
                label:  Complete
                allowed_transitions: []

        transitions:
            cancel:
                label:    Cancel
                step_to:  cancelled
                transition_definition: cancel_definition
            hold_pending:
                label:    Hold
                step_to:  pending_on_hold
                transition_definition: hold_definition
                form_options:
                    attribute_fields:
                        note:
                            form_type: textarea
                            options:
                                required: false
            un_hold_pending:
                label:    Un-Hold
                step_to:  pending
                transition_definition: un_hold_definition
            hold_invoice:
                label:    Hold
                step_to:  invoice_on_hold
                transition_definition: hold_definition
                form_options:
                    attribute_fields:
                        note:
                            form_type: textarea
                            options:
                                required: false
            un_hold_invoice:
                label:    Un-Hold
                step_to:  invoice
                transition_definition: un_hold_definition
            invoice:
                label:    Invoice
                step_to:  invoice
                transition_definition: invoice_definition
                form_options:
                    attribute_fields:
                        payment_reference:
                            form_type: text
                            options:
                                required: true
                                constraints:
                                  - NotBlank: ~
                        payment_details:
                            form_type: text
                            options:
                                required: true
                                constraints:
                                  - NotBlank: ~
                        invoiced_at:
                            form_type: oro_datetime
                            options:
                                required: true
                                constraints:
                                  - NotBlank: ~
                                  - DateTime: ~
            ship:
                label:    Ship
                step_to:  shipped
                transition_definition: ship_definition
                form_options:
                    attribute_fields:
                        shipping_reference:
                            form_type: text
                            options:
                                required: true
                                constraints:
                                  - NotBlank: ~
                        track_and_trace_number:
                            form_type: text
                            options:
                                required: true
                                constraints:
                                  - NotBlank: ~
                        shipped_at:
                            form_type: oro_datetime
                            options:
                                required: true
                                constraints:
                                  - NotBlank: ~
                                  - DateTime: ~
            credit:
                label:    Credit
                step_to:  credit
                transition_definition: credit_definition
            prepare_shipping:
                label:    Prepare Shipping
                step_to:  pick_and_pack
                transition_definition: prepare_shipping_definition
            payment_reminder:
                label:    Payment Reminder
                step_to:  pending
                transition_definition: payment_reminder_definition

        transition_definitions:
            cancel_definition:
                post_actions:
                    - @marello_cancel_order: ~
                    - @marello_notification_send:
                        entity: $order
                        recipient: $order.billingAddress.email
                        template: marello_order_cancelled
            hold_definition: []
            un_hold_definition: []
            invoice_definition:
                post_actions:
                    - @assign_value:
                        attribute: $order.paymentReference
                        value: $payment_reference
                    - @assign_value:
                        attribute: $order.paymentDetails
                        value: $payment_details
                    - @assign_value:
                        attribute: $order.invoicedAt
                        value: $invoiced_at
                    - @marello_notification_send:
                        entity: $order
                        recipient: $order.billingAddress.email
                        template: marello_order_invoiced
            credit_definition:
                post_actions:
                    - @marello_notification_send:
                        entity: $order
                        recipient: $order.billingAddress.email
                        template: marello_order_credited
            prepare_shipping_definition: []
            ship_definition:
                post_actions:
                    - @marello_ship_order: ~
                    - @marello_notification_send:
                        entity: $order
                        recipient: $order.billingAddress.email
                        template: marello_order_shipped_confirmation
            payment_reminder_definition:
                post_actions:
                    - @marello_notification_send:
                        entity: $order
                        recipient: $order.billingAddress.email
                        template: marello_order_payment_reminder
                    - @flash_message:
                        message: 'Reminder has been sent.'
