services:
    _defaults:
        public: true

    marello.importexport.controller:
        class: 'Marello\Bundle\ImportExportBundle\Controller\ImportExportController'
        decorates: 'Oro\Bundle\ImportExportBundle\Controller\ImportExportController'
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
