oro_workflow_bundle:
    resource:     "@!OroWorkflowBundle/Controller"
    type:         annotation

oro_workflow_bundle_api:
    resource:     "@!OroWorkflowBundle/Resources/config/oro/routing_api.yml"
    requirements:
        version:  latest|v1
        _format:  json
    defaults:
        version:  latest

marello_workflow_bundle_api:
    resource:     "@MarelloExtendWorkflowBundle/Resources/config/oro/routing_api.yml"
