marello_api_workflow_start:
    path: /api/workflow/start/{entityId}/{workflowName}/{transitionName}
    methods: [GET]
    defaults:
        _controller: MarelloExtendWorkflowBundle:Api\RestApiWorkflow:start
        _action: start_workflow
    requirements:
        entityId: \d+
    options:
        group: rest_api
        priority: 10

marello_api_workflow_transit:
    path: /api/workflow/transit/{workflowItemId}/{transitionName}
    methods: [GET]
    defaults:
        _controller: MarelloExtendWorkflowBundle:Api\RestApiWorkflow:transit
        _action: transit_workflow
    requirements:
        workflowItemId: \d+
    options:
        group: rest_api
        priority: 10

marello_api_workflow_activate:
    path: /api/workflow/activate/{workflowDefinitionId}
    methods: [GET]
    defaults:
        _controller: MarelloExtendWorkflowBundle:Api\RestApiWorkflow:activate
        _action: activate_workflow
    options:
        group: rest_api
        priority: 10

marello_api_workflow_deactivate:
    path: /api/workflow/deactivate/{workflowDefinitionId}
    methods: [GET]
    defaults:
        _controller: MarelloExtendWorkflowBundle:Api\RestApiWorkflow:deactivate
        _action: deactivate_workflow
    options:
        group: rest_api
        priority: 10
