services:
    marello_inventory.form.type.warehouse:
        class: Marello\Bundle\InventoryBundle\Form\Type\WarehouseType
        tags:
            - { name: form.type, alias: marello_warehouse }

    marello_inventory.form.type.product_inventory:
        class: Marello\Bundle\InventoryBundle\Form\Type\ProductInventoryType
        tags:
             - { name: form.type, alias: marello_product_inventory }

    marello_inventory.form.type.variant_inventory:
        class: Marello\Bundle\InventoryBundle\Form\Type\VariantInventoryType
        tags:
             - { name: form.type, alias: marello_variant_inventory }

    marello_inventory.form.type.inventory_item_collection:
        class: Marello\Bundle\InventoryBundle\Form\Type\InventoryItemCollectionType
        arguments:
            - @marello_inventory.form.subscriber.inventory_item_collection
        tags:
            - { name: form.type, alias: marello_inventory_item_collection }

    marello_inventory.form.type.inventory_item:
        class: Marello\Bundle\InventoryBundle\Form\Type\InventoryItemType
        tags:
            - { name: form.type, alias: marello_inventory_item }

    marello_inventory.form.subscriber.inventory_item_collection:
        class: Marello\Bundle\InventoryBundle\Form\Subscriber\InventoryItemCollectionSubscriber
        arguments:
            - @doctrine

    ## forms
    marello_inventory.form.product_inventory:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - 'marello_product_inventory'
            - 'marello_product_inventory'

    ## form handlers
    marello_inventory.form.handler.product_inventory:
        class: Marello\Bundle\InventoryBundle\Form\Handler\ProductInventoryHandler
        scope: request
        arguments:
            - @marello_inventory.form.product_inventory
            - @request
            - @doctrine.orm.entity_manager
            - @marello_inventory.logging.inventory_logger
