services:
    marello_inventory.importexport.data_converter:
        class: Marello\Bundle\InventoryBundle\ImportExport\DataConverter\InventoryLevelImportDataConverter

    marello_inventory.importexport.template_fixture.data_converter.inventorylevel:
        parent: oro_importexport.data_converter.template_fixture.configurable

    # Inventory level Reader
    marello_inventory.importexport.reader.inventory_level:
        class: Marello\Bundle\InventoryBundle\ImportExport\Reader\InventoryLevelReader
        arguments:
            - '@oro_importexport.context_registry'
            - '@doctrine'

    # Inventory level template Reader
    marello_inventory.importexport.reader.inventory_level_template:
        class: Marello\Bundle\InventoryBundle\ImportExport\Reader\InventoryLevelTemplateReader
        arguments:
            - '@oro_importexport.context_registry'
            - '@oro_importexport.template_fixture.manager'

    # Strategy
    marello_inventory.importexport.strategy.inventory.add_or_replace:
        class: Marello\Bundle\InventoryBundle\ImportExport\Strategy\InventoryLevelUpdateStrategy
        parent: oro_importexport.strategy.configurable_add_or_replace
        calls:
            - [setTokenAccessor, ['@oro_security.token_accessor']]

    # Import processor
    marello_inventory.importexport.processor.import.add_or_replace:
        parent: oro_importexport.processor.import_abstract
        calls:
            - [setDataConverter, ['@marello_inventory.importexport.data_converter']]
            - [setStrategy, ['@marello_inventory.importexport.strategy.inventory.add_or_replace']]
        tags:
            - { name: oro_importexport.processor, type: import, entity: 'Marello\Bundle\InventoryBundle\Entity\InventoryLevel', alias: marello_inventory.add_or_replace }
            - { name: oro_importexport.processor, type: import_validation, entity: 'Marello\Bundle\InventoryBundle\Entity\InventoryLevel', alias: marello_inventory.add_or_replace }

    # Export processor
    marello_inventory.importexport.processor.export:
        parent: oro_importexport.processor.export_abstract
        tags:
            - { name: oro_importexport.processor, type: export, entity: 'Marello\Bundle\InventoryBundle\Entity\InventoryLevel', alias: marello_inventorlevel_export }

    marello_inventory.importexport.processor.export_template:
        parent: oro_importexport.processor.export_abstract
        tags:
            - { name: oro_importexport.processor, type: export_template, entity: 'Marello\Bundle\InventoryBundle\Entity\InventoryLevel', alias: marello_inventorlevel_export }

    marello_inventory.importexport.template_fixture.inventorylevel:
        class: 'Marello\Bundle\InventoryBundle\ImportExport\TemplateFixture\InventoryLevelFixture'

        tags:
            - { name: oro_importexport.template_fixture }

    marello_inventory.importexport.template_fixture.warehouse:
        class: 'Marello\Bundle\InventoryBundle\ImportExport\TemplateFixture\WarehouseFixture'
        tags:
            - { name: oro_importexport.template_fixture }
