parameters:
    marello_inventory.warehouse.repository.class:      Marello\Bundle\InventoryBundle\Entity\Repository\WarehouseRepository
    marello_inventory.inventory_item.repository.class: Marello\Bundle\InventoryBundle\Entity\Repository\InventoryItemRepository

    marello_inventory.warehouse.entity.class:      Marello\Bundle\InventoryBundle\Entity\Warehouse
    marello_inventory.inventory_item.entity.class: Marello\Bundle\InventoryBundle\Entity\InventoryItem

    marello_inventory.allocation.allocator.class: Marello\Component\Inventory\InventoryAllocation\InventoryAllocator

    marello_inventory.event_listener.doctrine.inventory_allocation.class: Marello\Bundle\InventoryBundle\EventListener\Doctrine\InventoryAllocationListener

services:
    marello_product.widget_provider.actions.variant_mass_inventory:
        parent: oro_ui.widget_provider.action_button.abstract
        arguments:
            - marello_variant_mass_inventory_button
            - marello_variant_mass_inventory_link
        tags:
            - { name: oro_ui.view_action_provider, group: product }

    marello_inventory.logging.chart_builder:
        class: Marello\Bundle\InventoryBundle\Logging\ChartBuilder
        arguments:
            - @doctrine
            - @oro_dashboard.datetime.helper
            - @translator

    marello_inventory.logging.inventory_logger:
        class: Marello\Component\Inventory\Logging\InventoryLogger
        arguments:
            - @doctrine
            - @security.token_storage

    marello_inventory.event_listener.doctrine.inventory_allocation:
        class: '%marello_inventory.event_listener.doctrine.inventory_allocation.class%'
        tags:
            - {name: doctrine.event_listener, event: prePersist, method: prePersist }
            - {name: doctrine.event_listener, event: preRemove, method: preRemove }

    marello_inventory.allocation.allocator:
        class: '%marello_inventory.allocation.allocator.class%'
        arguments:
          - @doctrine

    marello_inventory.warehouse.repository:
        class: '%marello_inventory.warehouse.repository.class%'
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - '%marello_inventory.warehouse.entity.class%'

    marello_inventory.inventory_item.repository:
        class: '%marello_inventory.inventory_item.repository.class%'
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - '%marello_inventory.inventory_item.entity.class%'
