services:
    marello_address.form.type.address:
        class: Marello\Bundle\AddressBundle\Form\Type\AddressType
        tags:
            - { name: form.type }

    marello_address.form.type.typed_address:
        class: Marello\Bundle\AddressBundle\Form\Type\TypedAddressType
        tags:
            - { name: form.type }
