
services:
    marello_address.formatter.address:
        class: Marello\Bundle\AddressBundle\Formatter\AddressFormatter
        arguments:
            - '@oro_locale.settings'
            - '@oro_locale.formatter.name'
            - '@property_accessor'

    marello_address.twig.address_extension:
        class: Marello\Bundle\AddressBundle\Twig\AddressExtension
        public: false
        arguments:
            - '@marello_address.formatter.address'
        tags:
            - { name: twig.extension }