api:
    entities:
        Marello\Bundle\PricingBundle\Entity\AssembledPriceList:
            documentation_resource: '@MarelloPricingBundle/Resources/doc/api/assembledpricelist.md'
            fields:
                createdAt:
                    exclude: true
                updatedAt:
                    exclude: true
            filters:
                exclusion_policy: all
                fields:
                    product:
                        data_type: string
                        property_path: product.sku
                        description: 'Filter prices by Product SKU'
                    createdAt:
                        exclude: true
                    updatedAt:
                        exclude: true
            actions:
                delete: false
                delete_list: false
                get_relationship: false
                add_relationship: false
                update_relationship: false
                delete_relationship: false
                get_subresource: false

        Marello\Bundle\PricingBundle\Entity\AssembledChannelPriceList:
            fields:
                saleschannel:
                    property_path: channel
                createdAt:
                    exclude: true
                updatedAt:
                    exclude: true
            filters:
                exclusion_policy: all
                fields:
                    product:
                        data_type: string
                        property_path: product.sku
                        description: 'Filter prices by Product SKU'
                    saleschannel:
                        data_type: string
                        property_path: channel.code
                        description: 'Filter prices by SalesChannel'
                    createdAt:
                        exclude: true
                    updatedAt:
                        exclude: true
            actions:
                delete: false
                delete_list: false
                get_relationship: false
                add_relationship: false
                update_relationship: false
                delete_relationship: false
                get_subresource: false

        Marello\Bundle\PricingBundle\Entity\PriceType:
            documentation_resource: '@MarelloPricingBundle/Resources/doc/api/pricetype.md'
            actions:
                create: false
                update: false
                delete: false
                delete_list: false
                get_relationship: false
                add_relationship: false
                update_relationship: false
                delete_relationship: false
                get_subresource: false

        Marello\Bundle\PricingBundle\Entity\ProductPrice:
            documentation_resource: '@MarelloPricingBundle/Resources/doc/api/productprice.md'
            fields:
                pricetype:
                    property_path: type
                createdAt:
                    exclude: true
                updatedAt:
                    exclude: true
            filters:
                exclusion_policy: all
                fields:
                    pricetype:
                        data_type: string
                        property_path: type
                        description: 'Filter prices by PriceType'
                    createdAt:
                        exclude: true
                    updatedAt:
                        exclude: true
            actions:
                delete: false
                delete_list: false
                get_relationship: false
                add_relationship: false
                update_relationship: false
                delete_relationship: false
                get_subresource: false

        Marello\Bundle\PricingBundle\Entity\ProductChannelPrice:
            fields:
                saleschannel:
                    property_path: channel
                pricetype:
                    property_path: type
                createdAt:
                    exclude: true
                updatedAt:
                    exclude: true
            filters:
                exclusion_policy: all
                fields:
                    pricetype:
                        data_type: string
                        property_path: type
                        description: 'Filter prices by PriceType'
                    saleschannel:
                        data_type: string
                        property_path: channel.code
                        description: 'Filter prices by SalesChannel'
                    createdAt:
                        exclude: true
                    updatedAt:
                        exclude: true
            actions:
                delete: false
                delete_list: false
                get_relationship: false
                add_relationship: false
                update_relationship: false
                delete_relationship: false
                get_subresource: false
