api:
    entity_aliases:
        Marello\Bundle\InventoryBundle\Entity\Warehouse:
            alias: marellowarehouse
            plural_alias: marellowarehouses

    entities:
        Marello\Bundle\InventoryBundle\Entity\Warehouse:
            # this entity does not have own Data API resource
            actions:
                update: false
                delete: false
                delete_list: false
                update_relationship: false
                delete_relationship: false