search:
    Marello\Bundle\InventoryBundle\Entity\Warehouse:
        alias:                          marello_warehouses
        route:
            name:                       marelloenterprise_inventory_warehouse_update
            parameters:
                id:                     id
        search_template: '@MarelloEnterpriseInventory/Warehouse/searchResult.html.twig'
        fields:
            -
                name:                   label
                target_type:            text
                target_fields:          [label]
            -
                name:                   code
                target_type:            text
                target_fields:          [code]

    Marello\Bundle\InventoryBundle\Entity\WarehouseGroup:
        alias:                          marello_warehousegroups
        route:
            name:                       marelloenterprise_inventory_warehousegroup_update
            parameters:
                id:                     id
        search_template: '@MarelloEnterpriseInventory/WarehouseGroup/searchResult.html.twig'
        fields:
            -
                name:                   name
                target_type:            text
                target_fields:          [name]