acls:
    marello_invoice_create:
        type: entity
        class: MarelloInvoiceBundle:AbstractInvoice
        permission: CREATE

    marello_invoice_view:
        type: entity
        class: MarelloInvoiceBundle:AbstractInvoice
        permission: VIEW

    marello_invoice_update:
        type: entity
        class: MarelloInvoiceBundle:AbstractInvoice
        permission: EDIT
