system_configuration:
    groups:
        notification_invoice:
            title: marello.notification.system_configuration.groups.notification_invoice.label
            priority: 90
    fields:
        marello_invoice.invoice_email_template:
            data_type: string
            type: 'Marello\Bundle\NotificationBundle\Form\Type\EmailTemplateSelectType'
            options:
                label: marello.notification.config.fields.invoice.invoice_email_template.label
                required: false
                entityName: Marello\Bundle\InvoiceBundle\Entity\Invoice
                placeholder: marello.notification.config.fields.email_template.placeholder
            priority: 100

    tree:
        system_configuration:
            marello:
                children:
                    notification:
                        children:
                            notification_configuration:
                                children:
                                    notification_invoice:
                                        children:
                                            - marello_invoice.invoice_email_template
        organization_configuration:
            marello:
                children:
                    notification:
                        children:
                            notification_configuration:
                                children:
                                    notification_invoice:
                                        children:
                                            - marello_invoice.invoice_email_template