parameters:

services:
    marello_return.form.type.return:
        class: Marello\Bundle\RMABundle\Form\Type\ReturnType
        arguments:
            - @marello_return.form.subscriber.return_type_subscriber
        tags:
            - { name: form.type, alias: marello_return }

    marello_return.form.type.return_api:
        class: Marello\Bundle\RMABundle\Form\Type\ReturnApiType
        arguments:
            - @marello_return.form.data_transformer.order_to_order_number
        tags:
            - { name: form.type, alias: marello_return_api }

    marello_return.form.type.return_item:
        class: Marello\Bundle\RMABundle\Form\Type\ReturnItemType
        tags:
            - { name: form.type, alias: marello_return_item }

    marello_return.form.type.return_item_api:
        class: Marello\Bundle\RMABundle\Form\Type\ReturnItemApiType
        tags:
            - { name: form.type, alias: marello_return_item_api }

    marello_return.form.type.return_item_collection:
        class: Marello\Bundle\RMABundle\Form\Type\ReturnItemCollectionType
        tags:
            - { name: form.type, alias: marello_return_item_collection }

    marello_return.form.subscriber.return_type_subscriber:
        class: Marello\Bundle\RMABundle\Form\Subscriber\ReturnTypeSubscriber

    marello_return.form.return_api:
            class: Symfony\Component\Form\Form
            factory_method: createNamed
            factory_service: form.factory
            arguments:
                - ~
                - 'marello_return_api'

    marello_return.form.handler.return_api:
        class: Marello\Bundle\RMABundle\Form\Handler\ReturnApiHandler
        scope: request
        arguments:
            - @marello_return.form.return_api
            - @request
            - @doctrine.orm.entity_manager
            - @oro_entity.routing_helper

    marello_return.form.data_transformer.order_to_order_number:
        class: Marello\Bundle\RMABundle\Form\DataTransformer\OrderToOrderNumberTransformer
        arguments:
            - @doctrine.orm.entity_manager
