Marello\Bundle\RefundBundle\Entity\Refund:
    constraints:
        - Marello\Bundle\RefundBundle\Validator\Constraints\RefundBalanceConstraint: ~
    properties:
        items:
            - Valid: ~

Marello\Bundle\RefundBundle\Entity\RefundItem:
    constraints:
        -   Marello\Bundle\CoreBundle\Validator\Constraints\GreaterThanOrEqualToValue:
                fields: [ originalItemQty, quantity ]
                errorPath: quantity
                message: 'marello.refund.refunditem.messages.error.quantity_refunded_gte'
    properties:
        refundAmount:
            -   GreaterThanOrEqual:
                    value: 0

