acls:
    marello_saleschannel_create:
        type: entity
        class: Marello\Bundle\SalesBundle\Entity\SalesChannel
        permission: CREATE

    marello_saleschannel_view:
        type: entity
        class: Marello\Bundle\SalesBundle\Entity\SalesChannel
        permission: VIEW

    marello_saleschannel_update:
        type: entity
        class: Marello\Bundle\SalesBundle\Entity\SalesChannel
        permission: EDIT

    marello_saleschannel_delete:
        type: entity
        class: Marello\Bundle\SalesBundle\Entity\SalesChannel
        permission: DELETE

    marello_sales_saleschannelgroup_delete:
        type: entity
        class: Marello\Bundle\SalesBundle\Entity\SalesChannelGroup
        permission: DELETE