api:
    entities:
        Marello\Bundle\SalesBundle\Entity\SalesChannel:
            documentation_resource: '@MarelloSalesBundle/Resources/doc/api/saleschannel.md'
            identifier_field_names: [code]
            fields:
                createdAt:
                    exclude: true
                updatedAt:
                    exclude: true
            filters:
                exclusion_policy: all
                fields:
                    createdAt:
                        exclude: true
                    updatedAt:
                        exclude: true
            actions:
                create: false
                update: false
                delete: false
                delete_list: false
                get_relationship: false
                add_relationship: false
                update_relationship: false
                delete_relationship: false
                get_subresource: false