search:
    Marello\Bundle\SalesBundle\Entity\SalesChannel:
        alias:                          marello_saleschannels
        route:
            name:                       marello_sales_saleschannel_index
            parameters:
                id:                     id
        search_template: '@MarelloSales/SalesChannel/searchResult.html.twig'
        fields:
            -
                name:                   name
                target_type:            text
                target_fields:          [name]

    #Marello\Bundle\SalesBundle\Entity\SalesChannelType:
    #    alias:                          marello_sales_channel_types
        #route:
        #    name:                       marello_sales_saleschannel_index
        #    parameters:
        #        id:                     id
        #search_template: '@MarelloSales/SalesChannelType/searchResult.html.twig'
        #fields:
        #    -
        #        name:                   name
        #        target_type:            text
        #        target_fields:          [name]