search:
    Marello\Bundle\SalesBundle\Entity\SalesChannel:
        alias:                          marello_saleschannels
        route:
            name:                       marello_sales_saleschannel_index
            parameters:
                id:                     id
        search_template: '@MarelloSales/SalesChannel/searchResult.html.twig'
        fields:
            -
                name:                   name
                target_type:            text
                target_fields:          [name]
