Marello\Component\Inventory\Entity\InventoryLog:
    type: entity
    table: marello_inventory_log
    repositoryClass: Marello\Component\Inventory\ORM\Repository\InventoryLogRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        oldQuantity:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        newQuantity:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        oldAllocatedQuantity:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        newAllocatedQuantity:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        actionType:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        createdAt:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
    manyToOne:
        user:
            targetEntity: Oro\Bundle\UserBundle\Entity\User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        order:
            targetEntity: Marello\Bundle\OrderBundle\Entity\Order
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                order_id:
                    referencedColumnName: id
            orphanRemoval: false
        inventoryItem:
            targetEntity: Marello\Component\Inventory\Entity\InventoryItem
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                inventoryItem_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
    lifecycleCallbacks:
        prePersist:
            - prePersist
