datagrid:
    marello-sales-channel:
        source:
            type: orm
            query:
                select:
                    - sc
                from:
                    - { table: MarelloSalesBundle:SalesChannel, alias: sc }
        columns:
            name:
                label:                marello.sales.saleschannel.name.label
                frontend_type:        string
            code:
                label:                marello.sales.saleschannel.code.label
                frontend_type:        string
            channelType:
                label:                marello.sales.saleschannel.channel_type.label
                frontend_type:        string
            currency:
                label:                marello.sales.saleschannel.currency.label
                frontend_type:        string
            active:
                label:                marello.sales.saleschannel.active.label
                frontend_type:        boolean
            default:
                label:                marello.sales.saleschannel.default.label
                frontend_type:        boolean
        properties:
            id: ~
            delete_link:
                type:   url
                route:  marello_sales_saleschannel_delete
                params: [ id ]
            edit_link:
                type:   url
                route:  marello_sales_saleschannel_update
                params: [ id ]
        actions:
            edit:
                type:          navigate
                link:          edit_link
                icon:          edit
                rowAction:     true
            delete:
                type:          delete
                link:          delete_link
                label:         oro.grid.action.delete
                confirmation:  true
                icon:          trash
        options:
            entityHint: sales_channel
            entity_pagination: true
