parameters:
    #form types
    marello_sales.form_type.saleschannel.class:           Marello\Bundle\SalesBundle\Form\Type\SalesChannelType
    #form handlers
    marello_sales.sales_form.handler.class:               Marello\Bundle\SalesBundle\Form\Handler\SalesChannelHandler
services:
    #form types
    marello_sales_form_type_saleschannel:
        class: %marello_sales.form_type.saleschannel.class%
        arguments:
            - @marello_sales.saleschannel.form_subscriber
        tags:
             - { name: form.type, alias: marello_sales_channel }
             
    marello_sales_form_type_saleschannel_multi_select:
        class: Marello\Bundle\SalesBundle\Form\Type\SalesChannelMultiSelectType
        arguments:
            - @marello_sales.form.data_transformer.sales_channel
        tags:
            - { name: form.type, alias: marello_sales_saleschannel_multi_select }

    marello_sales_form_type_saleschannel_select:
        class: Marello\Bundle\SalesBundle\Form\Type\SalesChannelSelectType
        tags:
            - { name: form.type, alias: marello_sales_saleschannel_select }

    #forms
    marello_sales.saleschannel.form:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - 'marello_sales_channel'
            - 'marello_sales_channel'

    #form handlers
    marello_sales.saleschannel_form.handler:
        class: %marello_sales.sales_form.handler.class%
        scope: request
        arguments:
            - @marello_sales.saleschannel.form
            - @request
            - @doctrine.orm.entity_manager

    #data transformer
    marello_sales.form.data_transformer.sales_channel:
        class: Oro\Bundle\FormBundle\Form\DataTransformer\EntitiesToIdsTransformer
        arguments:
            - @doctrine.orm.entity_manager
            - MarelloSalesBundle:SalesChannel
