services:
    MarelloEnterprise\Bundle\OrderBundle\Form\Extension\OrderExtension:
        arguments:
            - '@oro_config.manager'
        tags:
            - { name: form.type_extension, alias: marello_order_order, extended_type: Marello\Bundle\OrderBundle\Form\Type\OrderType }
