services:
    MarelloEnterprise\Bundle\OrderBundle\EventListener\Doctrine\OrderWorkflowStartListener:
        decorates: marello_order.listener.start_workflow
        arguments:
            - '@oro_workflow.manager'
        calls:
            - [setTokenAccessor, ['@oro_security.token_accessor']]