services:
    MarelloEnterprise\Bundle\OrderBundle\Provider\OrderConsolidationProvider:
        arguments:
            - '@oro_config.manager'

    MarelloEnterprise\Bundle\OrderBundle\Provider\Form\OrderConsolidationFormChangesProvider:
        arguments:
            - '@MarelloEnterprise\Bundle\OrderBundle\Provider\OrderConsolidationProvider'
        tags:
            - { name: marello.form_changes_data_provider, class: 'Marello\Bundle\OrderBundle\Entity\Order', type: consolidation_enabled, priority: 255 }
