services:
    marelloenterprise_replenishment.form.type.replenishment_order_config:
        class: 'MarelloEnterprise\Bundle\ReplenishmentBundle\Form\Type\ReplenishmentOrderConfigType'
        arguments:
            - "@router"
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type }

    marelloenterprise_replenishment.form.type.replenishment_order_item:
        class: 'MarelloEnterprise\Bundle\ReplenishmentBundle\Form\Type\ReplenishmentOrderItemType'
        tags:
            - { name: form.type }

    marelloenterprise_replenishment.form.type.replenishment_order_item_collection:
        class: 'MarelloEnterprise\Bundle\ReplenishmentBundle\Form\Type\ReplenishmentOrderItemCollectionType'
        tags:
            - { name: form.type }

    marelloenterprise_replenishment.form.type.replenishment_strategy_choice:
        class: 'MarelloEnterprise\Bundle\ReplenishmentBundle\Form\Type\ReplenishmentStrategyChoiceType'
        arguments:
            - '@marelloenterprise_replenishment.provider.replenishment_strategies_choices_provider'
        tags:
            - { name: form.type }

    marelloenterprise_replenishment.form.type.replenishment_order_config_products:
        class: 'MarelloEnterprise\Bundle\ReplenishmentBundle\Form\Type\ReplenishmentOrderConfigProductsType'
        arguments:
            - '@security.authorization_checker'
        tags:
            - { name: form.type }

    marelloenterprise_replenishment.form.handler.replenishment_order_config:
        class: 'MarelloEnterprise\Bundle\ReplenishmentBundle\Form\Handler\ReplenishmentOrderConfigHandler'
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@marelloenterprise_replenishment.provider.replenishment_orders_from_config'

    MarelloEnterprise\Bundle\ReplenishmentBundle\Form\Type\ReplenishmentOrderManualItemType:
        arguments:
            - '@translator'
        tags:
            - { name: form.type }
