imports:
    - { resource: controllers.yml }

services:
    marelloenterprise_replenishment.replenishment_strategy.registry:
        class: 'MarelloEnterprise\Bundle\ReplenishmentBundle\Strategy\ReplenishmentStrategiesRegistry'

    marelloenterprise_replenishment.replenishment_strategy.equal_division:
        class: 'MarelloEnterprise\Bundle\ReplenishmentBundle\Strategy\EqualDivision\EqualDivisionReplenishmentStrategy'
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: marello_replenishment_strategy }

    marelloenterprise_replenishment.replenishment_strategy.manual:
        class: 'MarelloEnterprise\Bundle\ReplenishmentBundle\Strategy\ManualReplenishmentStrategy'
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: marello_replenishment_strategy }

    marelloenterprise_replenishment.provider.replenishment_strategies_choices_provider:
        class: 'MarelloEnterprise\Bundle\ReplenishmentBundle\Provider\ReplenishmentStrategyChoicesProvider'
        arguments:
            - '@marelloenterprise_replenishment.replenishment_strategy.registry'
            - '@translator'

    marelloenterprise_replenishment.provider.replenishment_orders_from_config:
        class: 'MarelloEnterprise\Bundle\ReplenishmentBundle\Provider\ReplenishmentOrdersFromConfigProvider'
        arguments:
            - '@marelloenterprise_replenishment.replenishment_strategy.registry'

    MarelloEnterprise\Bundle\ReplenishmentBundle\Entity\Repository\ReplenishmentOrderRepository:
        parent: oro_entity.abstract_repository
        arguments:
            - 'MarelloEnterprise\Bundle\ReplenishmentBundle\Entity\ReplenishmentOrder'
        tags:
            - { name: doctrine.repository_service }

    marelloenterprise_replenishment.twig.replenishment_extension:
        class: 'MarelloEnterprise\Bundle\ReplenishmentBundle\Twig\ReplenishmentExtension'
        arguments:
            - '@marelloenterprise_replenishment.replenishment_strategy.registry'
            - '@translator.default'
        tags:
            - { name: twig.extension }

    marelloenterprise_replenishment.listener.doctrine.workflow_transit:
        class: 'MarelloEnterprise\Bundle\ReplenishmentBundle\EventListener\Doctrine\ReplenishmentWorkflowAllocateInventoryListener'
        arguments:
            - '@oro_workflow.manager'
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postFlush }

    marelloenterprise_replenishment.entity_listener.repl_order_item:
        class: 'MarelloEnterprise\Bundle\ReplenishmentBundle\EventListener\Doctrine\ReplenishmentOrderItemListener'
        arguments:
            - '@event_dispatcher'
            - '@translator.default'
        tags:
            - { name: doctrine.orm.entity_listener, entity: 'MarelloEnterprise\Bundle\ReplenishmentBundle\Entity\ReplenishmentOrderItem', event: postUpdate }

    marelloenterprise_replenishment.async.allocate_replenishment_orders_inventory_processor:
        class: 'MarelloEnterprise\Bundle\ReplenishmentBundle\Async\AllocateReplenishmentOrdersInventoryProcessor'
        arguments:
            - '@logger'
            - '@doctrine.orm.entity_manager'
            - '@oro_workflow.manager'
        tags:
            - { name: 'oro_message_queue.client.message_processor' }

    marelloenterprise_replenishment.command.allocate_delayed_replenishment_orders_inventory:
        class: 'MarelloEnterprise\Bundle\ReplenishmentBundle\Command\AllocateDelayedReplenishmentOrdersInventoryCommand'
        arguments:
            - '@doctrine'
            - '@oro_message_queue.client.message_producer'
        tags:
            - { name: console.command }

    MarelloEnterprise\Bundle\ReplenishmentBundle\Provider\ReplenishmentManualItemFormChangesProvider:
        arguments:
            - '@oro_entity.doctrine_helper'
        tags:
            - { name: marello.form_changes_data_provider, class: 'MarelloEnterprise\Bundle\ReplenishmentBundle\Entity\ReplenishmentOrderConfig', type: manualItems, priority: 0 }
