services:
    # Form Event Listeners / Subscribers
    marello_purchase_order.form.event_listener.purchase_order_item_subscriber:
        class: Marello\Bundle\PurchaseOrderBundle\Form\EventListener\PurchaseOrderItemSubscriber
        arguments:
            - '@translator'

    # Form Types
    marello_purchase_order.form.type.purchase_order:
        class: Marello\Bundle\PurchaseOrderBundle\Form\Type\PurchaseOrderType
        tags:
            - { name: form.type }

    marello_purchase_order.form.type.purchase_order_create_step_two:
        class: Marello\Bundle\PurchaseOrderBundle\Form\Type\PurchaseOrderCreateStepTwoType
        arguments:
            - '@router'
            - '@oro_currency.helper.currency_name'
        tags:
            - { name: form.type }

    marello_purchase_order.form.type.purchase_order_item:
        class: Marello\Bundle\PurchaseOrderBundle\Form\Type\PurchaseOrderItemType
        tags:
            - { name: form.type }

    marello_purchase_order.form.type.purchase_order_advised_item_collection:
        class: Marello\Bundle\PurchaseOrderBundle\Form\Type\PurchaseOrderAdvisedItemCollectionType
        tags:
            - { name: form.type }

    marello_purchase_order.form.type.purchase_order_item_collection:
        class: Marello\Bundle\PurchaseOrderBundle\Form\Type\PurchaseOrderItemCollectionType
        tags:
            - { name: form.type }

    marello_purchase_order.form.type.partial_receive:
        class: Marello\Bundle\PurchaseOrderBundle\Form\Type\PartialReceiveType
        tags:
            - { name: form.type }

    marello_purchase_order.form.type.po_item_receive:
        class: Marello\Bundle\PurchaseOrderBundle\Form\Type\PurchaseOrderItemReceiveType
        arguments:
            - '@marello_purchase_order.form.event_listener.purchase_order_item_subscriber'
        tags:
            - { name: form.type }

    marello_purchase_order.form.type.po_item_receive_collection:
        class: Marello\Bundle\PurchaseOrderBundle\Form\Type\PurchaseOrderItemReceiveCollectionType
        tags:
            - { name: form.type }

    # Forms
    marello_purchase_order.form.purchase_order:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', 'create']
        arguments:
            - Marello\Bundle\PurchaseOrderBundle\Form\Type\PurchaseOrderType

    marello_purchase_order.form.purchase_order_create_step_two:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', 'create']
        arguments:
            - Marello\Bundle\PurchaseOrderBundle\Form\Type\PurchaseOrderCreateStepTwoType

    # Handlers
    marello_purchase_order.form.handler.purchase_order_create:
        class: Marello\Bundle\PurchaseOrderBundle\Form\Handler\PurchaseOrderCreateHandler
        public: true
        arguments:
            - '@marello_purchase_order.form.purchase_order_create_step_two'
            - '@request_stack'
            - '@doctrine'
            - '@security.token_storage'

    marello_purchase_order.form.handler.purchase_order_update:
        class: Marello\Bundle\PurchaseOrderBundle\Form\Handler\PurchaseOrderUpdateHandler
        public: true
        arguments:
            - '@marello_purchase_order.form.purchase_order'
            - '@request_stack'
            - '@doctrine.orm.entity_manager'
