parameters:
    marello_purchaseorder.entity.purchaseorder.class: Marello\Bundle\PurchaseOrderBundle\Entity\PurchaseOrder

services:
    marello_purchaseorder.processor.note_activity_processor:
        class: Marello\Bundle\PurchaseOrderBundle\Processor\NoteActivityProcessor
        arguments:
            - '@marello_purchaseorder.oro_note_entity_service'
            - '@doctrine.orm.entity_manager'

    marello_purchaseorder.oro_note_entity_service:
        class: '%oro_note.entity.class%'

    marello_purchaseorder.workflow.receive_purchase_order:
        class: Marello\Bundle\PurchaseOrderBundle\Workflow\Action\ReceivePurchaseOrderAction
        arguments:
            - '@oro_action.expression.context_accessor'
            - '@doctrine.orm.entity_manager'
            - '@marello_purchaseorder.processor.note_activity_processor'
        tags:
            - { name: oro_action.action, alias: marello_receive_purchase_order }

    marello_purchaseorder.workflow.send_purchase_order:
        class: Marello\Bundle\PurchaseOrderBundle\Workflow\Action\SendPurchaseOrderAction
        parent: marello_notification.workflow.send_notification_action
        tags:
            - { name: oro_action.action, alias: marello_purchase_order_send }

    marello_purchaseorder.workflow.action.transit_complete_action:
        class: Marello\Bundle\PurchaseOrderBundle\Workflow\Action\TransitCompleteAction
        parent: marello_core.workflow.action.workflow_transit_action
        tags:
            - { name: oro_action.action, alias: marello_purchase_order_transit_complete_action }

    marello_purchaseorder.listener.datagrid.product_supplier_grid_listener:
        class: Marello\Bundle\ProductBundle\EventListener\Datagrid\ProductSupplierGridListener
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.before.marello-purchase-order-item-candidates, method: buildBeforeProductsBySupplier, priority: 100 }

    marello_purchaseorder.listener.datagrid.purchaseorder_grid_listener:
        class: Marello\Bundle\PurchaseOrderBundle\EventListener\Datagrid\PurchaseOrderGridListener
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@oro_workflow.manager'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.before.marello-purchase-order-item-candidates, method: buildBeforePendingOrders }

    marello_purchaseorder.twig.purchaseorder_extension:
        class: Marello\Bundle\PurchaseOrderBundle\Twig\PurchaseOrderExtension
        arguments:
            - '@oro_workflow.manager'
        tags:
            - { name: twig.extension }

    marello_purchaseorder.listener.doctrine.warehouse_listener:
        class: Marello\Bundle\PurchaseOrderBundle\EventListener\Doctrine\PurchaseOrderWarehouseListener
        arguments:
            - '@doctrine'
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    marello_purchaseorder.listener.doctrine.workflow_transit:
        class: Marello\Bundle\PurchaseOrderBundle\EventListener\Doctrine\PurchaseOrderWorkflowTransitListener
        arguments:
            - '@oro_workflow.manager'
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postFlush }

    marello_purchaseorder.api.add_workflow_item_config:
        class: 'Marello\Bundle\ExtendWorkflowBundle\Api\Processor\ProcessWorkflowItemConfig'
        tags:
            - { name: oro.api.processor, action: get_config,  class: Marello\Bundle\PurchaseOrderBundle\Entity\PurchaseOrder }

    marello_purchaseorder.api.add_workflow_item:
        class: 'Marello\Bundle\ExtendWorkflowBundle\Api\Processor\ProcessWorkflowItem'
        arguments:
            - '@oro_workflow.manager'
            - '@oro_entity.doctrine_helper'
            - '@translator.default'
        tags:
            - { name: oro.api.processor, action: customize_loaded_data,  class: Marello\Bundle\PurchaseOrderBundle\Entity\PurchaseOrder }
