services:
    marello_shipping.mass_action.status.enable:
        class: 'Marello\Bundle\RuleBundle\Datagrid\Extension\MassAction\Actions\StatusEnableMassAction'
        arguments:
            - 'marello_shipping.mass_action.status_handler'
            - 'marello_status_shipping_rule_massaction'
            - true
        public: true
        shared: false
        tags:
            - { name: oro_datagrid.extension.mass_action.type, type: marelloshippingruleenable }

    marello_shipping.mass_action.status.disable:
        class: 'Marello\Bundle\RuleBundle\Datagrid\Extension\MassAction\Actions\StatusEnableMassAction'
        arguments:
            - 'marello_shipping.mass_action.status_handler'
            - 'marello_status_shipping_rule_massaction'
            - false
        public: true
        shared: false
        tags:
            - { name: oro_datagrid.extension.mass_action.type, type: marelloshippingruledisable }

    marello_shipping.mass_action.status_handler:
        class: 'Marello\Bundle\RuleBundle\Datagrid\Extension\MassAction\StatusMassActionHandler'
        public: true
        arguments:
            - 'marello.shipping.datagrid.status.success_message'
            - Marello\Bundle\ShippingBundle\Entity\ShippingMethodsConfigsRule
            - '@doctrine.orm.entity_manager'
            - '@translator'
#            - '@oro_security.security_facade.link'
