services:
    marello_shipping.disable_integration_listener:
        class: 'Marello\Bundle\ShippingBundle\Method\EventListener\ShippingMethodDisableIntegrationListener'
        abstract: true

    marello_shipping.remove_integration_listener:
        class: 'Marello\Bundle\ShippingBundle\Method\EventListener\IntegrationRemovalListener'
        abstract: true

    marello_shipping.admin_view.method_template.listener:
        class: 'Marello\Bundle\ShippingBundle\EventListener\ShippingRuleViewMethodTemplateListener'
        abstract: true

    marello_shipping.method.event_listener.type_removal:
        class: 'Marello\Bundle\ShippingBundle\Method\EventListener\MethodAndTypeRemovalListener'
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@logger'
        tags:
            - { name: kernel.event_listener, event: marello_shipping.method_removal, method: onMethodRemove }
            - { name: kernel.event_listener, event: marello_shipping.method_type_removal, method: onMethodTypeRemove }

    marello_shipping.method.event_listener.method_renaming:
        class: 'Marello\Bundle\ShippingBundle\Method\EventListener\MethodRenamingListener'
        arguments:
            - '@marello_shipping.repository.shipping_method_config'
        tags:
            - { name: kernel.event_listener, event: marello_shipping.method_renaming, method: onMethodRename}
