parameters:
    marello_shipping.entity.shipping_methods_configs_rule.class:  Marello\Bundle\ShippingBundle\Entity\ShippingMethodsConfigsRule
    marello_shipping.rule_grid_route_name: 'marello_shipping_methods_configs_rule_index'
    marello_shipping.rule_grid_name: 'marello-shipping-methods-configs-rule-grid'
services:
    marello_shipping.integration.shipping_service_registry:
        class: Marello\Bundle\ShippingBundle\Integration\ShippingServiceRegistry

    marello_shipping.workflow.action.create:
        class: Marello\Bundle\ShippingBundle\Workflow\ShipmentCreateAction
        arguments:
            - '@oro_action.expression.context_accessor'
            - '@doctrine'
            - '@marello_shipping.shipping_method_provider'
        tags:
            - { name: oro_action.action, alias: marello_shipment_create }

    marello_shipping.integration.ups.api:
        class: Marello\Bundle\ShippingBundle\Integration\UPS\UPSApi
        arguments:
            - '@oro_config.manager'

    marello_shipping.integration.ups.service_integration:
        class: Marello\Bundle\ShippingBundle\Integration\UPS\UPSShippingServiceIntegration
        arguments:
            - '@marello_shipping.integration.ups.api'
            - '@doctrine'
            - '@oro_attachment.manager'
            - '@marello_shipping.integration.ups.request_builder.shipment_confirm'
            - '@marello_shipping.integration.ups.request_builder.shipment_accept'
        tags:
            - { name: marello.shipping.integration, alias: ups }

    marello_shipping.integration.ups.service_data_factory:
        class: Marello\Bundle\ShippingBundle\Integration\UPS\UPSShippingServiceDataFactory
        arguments:
            - '@oro_config.manager'
            - '@doctrine'
        tags:
            - { name: marello.shipping.data_factory, alias: ups }

    marello_shipping.integration.manual.service_integration:
        class: Marello\Bundle\ShippingBundle\Integration\Manual\ManualShippingServiceIntegration
        arguments:
            - '@doctrine'
        tags:
            - { name: marello.shipping.integration, alias: manual }

    marello_shipping.integration.manual.service_data_factory:
        class: Marello\Bundle\ShippingBundle\Integration\Manual\ManualShippingServiceDataFactory
        arguments:
            - '@oro_config.manager'
            - '@doctrine'
        tags:
            - { name: marello.shipping.data_factory, alias: manual }

    # UPS Request buiders
    marello_shipping.integration.ups.request_builder.shipment_confirm:
        class: Marello\Bundle\ShippingBundle\Integration\UPS\RequestBuilder\ShipmentConfirmRequestBuilder
        arguments:
            - '@oro_config.manager'

    marello_shipping.integration.ups.request_builder.shipment_accept:
        class: Marello\Bundle\ShippingBundle\Integration\UPS\RequestBuilder\ShipmentAcceptRequestBuilder
        arguments:
            - '@oro_config.manager'

    marello_shipping.datagrid.shipping_rule_actions_visibility_provider:
        parent: marello_rule.action.visibility_provider

    marello_shipping.provider.basic_shipping_methods_choices:
        class: Marello\Bundle\ShippingBundle\Provider\BasicShippingMethodChoicesProvider
        arguments:
        - '@marello_shipping.shipping_method_provider'
        - '@translator'

    marello_shipping.shipping_methods_choices_provider.enabled_methods_decorator:
         class: 'Marello\Bundle\ShippingBundle\Provider\EnabledShippingMethodChoicesProviderDecorator'
         public: false
         decorates: marello_shipping.provider.basic_shipping_methods_choices
         decoration_priority: 255
         arguments:
             - '@marello_shipping.shipping_method_provider'
             - '@marello_shipping.shipping_methods_choices_provider.enabled_methods_decorator.inner'

    marello_shipping.checker.shipping_method_enabled:
        class: 'Marello\Bundle\ShippingBundle\Checker\ShippingMethodEnabledByIdentifierChecker'
        arguments:
            - '@marello_shipping.shipping_method_provider'

    marello_shipping.checker.shipping_rule_enabled:
        class: 'Marello\Bundle\ShippingBundle\Checker\ShippingRuleEnabledChecker'
        arguments:
            - '@marello_shipping.checker.shipping_method_enabled'

    marello_shipping.method.view_factory:
        class: 'Marello\Bundle\ShippingBundle\Method\ShippingMethodViewFactory'
        public: false
        arguments:
            - '@marello_shipping.shipping_method_provider'

    marello_shipping.method.composed_configuration_builder_factory:
        class: 'Marello\Bundle\ShippingBundle\Method\Configuration\Composed\ComposedShippingMethodConfigurationBuilderFactory'
        public: false

    marello_shipping.method.event.dispatcher.method_removal:
        class: 'Marello\Bundle\ShippingBundle\Method\Event\BasicMethodRemovalEventDispatcher'
        public: false
        arguments:
            - '@event_dispatcher'

    marello_shipping.method.event.dispatcher.type_removal:
        class: 'Marello\Bundle\ShippingBundle\Method\Event\BasicMethodTypeRemovalEventDispatcher'
        public: false
        arguments:
            - '@event_dispatcher'

    marello_shipping.method.event_listener.type_removal:
        class: 'Marello\Bundle\ShippingBundle\Method\EventListener\MethodAndTypeRemovalListener'
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@logger'
        tags:
            - { name: kernel.event_listener, event: marello_shipping.method_removal, method: onMethodRemove }
            - { name: kernel.event_listener, event: marello_shipping.method_type_removal, method: onMethodTypeRemove }

    marello_shipping.method.event_listener.method_renaming:
        class: 'Marello\Bundle\ShippingBundle\Method\EventListener\MethodRenamingListener'
        arguments:
            - '@marello_shipping.repository.shipping_method_config'
        tags:
            - { name: kernel.event_listener, event: marello_shipping.method_renaming, method: onMethodRename}

    marello_shipping.method.event.dispatcher.method_renaming:
        class: 'Marello\Bundle\ShippingBundle\Method\Event\BasicMethodRenamingEventDispatcher'
        arguments:
            - '@event_dispatcher'

    marello_shipping.repository.shipping_method_config:
        class: 'Marello\Bundle\ShippingBundle\Entity\Repository\ShippingMethodConfigRepository'
        parent: oro_entity.abstract_repository
        arguments:
            - 'Marello\Bundle\ShippingBundle\Entity\ShippingMethodConfig'

    marello_shipping.repository.shipping_methods_configs_rule:
        class: 'Marello\Bundle\ShippingBundle\Entity\Repository\ShippingMethodsConfigsRuleRepository'
        parent: oro_entity.abstract_repository
        arguments:
            - 'Marello\Bundle\ShippingBundle\Entity\ShippingMethodsConfigsRule'
        calls:
            - [setAclHelper, ['@oro_security.acl_helper']]

    marello_shipping.method_disable_handler.basic:
        class: 'Marello\Bundle\ShippingBundle\Method\Handler\BasicShippingMethodDisableHandler'
        public: false

    marello_shipping.method_disable_handler.decorator:
        class: 'Marello\Bundle\ShippingBundle\Method\Handler\RulesShippingMethodDisableHandlerDecorator'
        decorates: marello_shipping.method_disable_handler.basic
        decoration_priority: 255
        public: false
        arguments:
            - '@marello_shipping.method_disable_handler.decorator.inner'
            - '@marello_shipping.repository.shipping_methods_configs_rule'
            - '@marello_shipping.shipping_method_provider'

    marello_shipping.rule_filtration.basic_service:
        class: 'Marello\Bundle\ShippingBundle\RuleFiltration\Basic\BasicMethodsConfigsRulesFiltrationService'
        arguments:
            - '@marello_rule.rule_filtration.service'
            - '@marello_shipping.converter.shipping_context_to_rule_values'

    marello_shipping.converter.shipping_context_to_rule_values:
        class: 'Marello\Bundle\ShippingBundle\Converter\Basic\ShippingContextToRulesValuesConverter'
        arguments:
            - '@marello_shipping.expression_language.decorated_product_line_item_factory'

    marello_shipping.expression_language.decorated_product_line_item_factory:
        class: 'Marello\Bundle\ShippingBundle\ExpressionLanguage\DecoratedProductLineItemFactory'
        arguments:
            - '@marello_product.virtual_fields.decorator_factory'

    marello_shipping.provider.methods_configs_rules.by_context.basic:
        class: 'Marello\Bundle\ShippingBundle\Provider\MethodsConfigsRule\Context\Basic\BasicMethodsConfigsRulesByContextProvider'
        public: false
        arguments:
            - '@marello_shipping.rule_filtration.basic_service'
            - '@marello_shipping.repository.shipping_methods_configs_rule'

    marello_shipping.shipping_price.provider:
        class: 'Marello\Bundle\ShippingBundle\Provider\Price\ShippingPriceProvider'
        arguments:
            - '@marello_shipping.provider.methods_configs_rules.by_context.basic'
            - '@marello_shipping.shipping_method_provider'
            - '@marello_shipping.shipping_price.provider.cache'
            - '@marello_shipping.method.view_factory'
            - '@event_dispatcher'

    marello_shipping.shipping_price.provider_enabled_methods_decorator:
        class: 'Marello\Bundle\ShippingBundle\Provider\Price\EnabledMethodsShippingPriceProviderDecorator'
        public: false
        decorates: marello_shipping.shipping_price.provider
        decoration_priority: 255
        arguments:
             - '@marello_shipping.shipping_price.provider_enabled_methods_decorator.inner'
             - '@marello_shipping.shipping_method_provider'

    marello_shipping.shipping_price.provider.cache:
        class: 'Marello\Bundle\ShippingBundle\Provider\Cache\ShippingPriceCache'
        arguments:
            - '@marello_shipping.price.cache'
            - '@marello_shipping.shipping_context.cache_key_generator'

    marello_shipping.price.cache:
        public: false
        parent: oro.cache.abstract
        calls:
            - [setNamespace, ['marello_shipping_price']]

    marello_shipping.shipping_context.cache_key_generator:
        class: 'Marello\Bundle\ShippingBundle\Context\ShippingContextCacheKeyGenerator'
        public: false

    marello_shipping.context.builder_factory_basic:
        class: 'Marello\Bundle\ShippingBundle\Context\Builder\Basic\Factory\BasicShippingContextBuilderFactory'

    marello_shipping.context.doctrine_line_item_collection_factory:
        class: 'Marello\Bundle\ShippingBundle\Context\LineItem\Collection\Doctrine\Factory\DoctrineShippingLineItemCollectionFactory'

    marello_shipping.line_item.factory_basic:
        class: 'Marello\Bundle\ShippingBundle\Context\LineItem\Builder\Basic\Factory\BasicShippingLineItemBuilderFactory'

    marello_shipping.line_item.factory_by_line_item_basic:
        class: 'Marello\Bundle\ShippingBundle\Context\LineItem\Builder\Basic\Factory\BasicLineItemBuilderByLineItemFactory'
        arguments:
            - '@marello_shipping.line_item.factory_basic'

    marello_shipping.shipping_rule.manager.api:
        class: 'Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager'
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - '%marello_shipping.entity.shipping_methods_configs_rule.class%'
            - "@doctrine.orm.entity_manager"

    marello_shipping.validator.enabled_type_config_validation_group:
        class: 'Marello\Bundle\ShippingBundle\Validator\Constraints\EnabledTypeConfigsValidationGroupValidator'
        tags:
            - { name: validator.constraint_validator, alias: marello_shipping_enabled_type_config_validation_group_validator }

    marello_shipping.validator.shipping_rule_enabled:
        class: 'Marello\Bundle\ShippingBundle\Validator\Constraints\ShippingRuleEnableValidator'
        arguments:
            - '@marello_shipping.checker.shipping_rule_enabled'
        tags:
            - { name: validator.constraint_validator, alias: marello_shipping_rule_enabled_validator }

    marello_shipping.method_validator.result_factory_common_parameter_bag:
        class: 'Marello\Bundle\ShippingBundle\Method\Validator\Result\Factory\Common\ParameterBag\ParameterBagCommonShippingMethodValidatorResultFactory'

    marello_shipping.method_validator.result_error_factory_common_parameter_bag:
        class: 'Marello\Bundle\ShippingBundle\Method\Validator\Result\Error\Factory\Common\ParameterBag\ParameterBagCommonShippingMethodValidatorResultErrorFactory'

    marello_shipping.method_validator_result_error_collection_builder_common:
        class: 'Marello\Bundle\ShippingBundle\Method\Validator\Result\Error\Collection\Builder\Common\Doctrine\DoctrineCommonShippingMethodValidatorResultErrorCollectionBuilder'

    marello_shipping.method_validator.main:
        parent: marello_shipping.method_validator.basic

    marello_shipping.method_validator.basic:
        class: 'Marello\Bundle\ShippingBundle\Method\Validator\Basic\BasicShippingMethodValidator'
        arguments:
            - '@marello_shipping.method_validator.result_factory_common_parameter_bag'


    marello_shipping.condition.has_applicable_shipping_methods:
        class: 'Marello\Bundle\ShippingBundle\Condition\HasApplicableShippingMethods'
        arguments:
            - '@marello_shipping.shipping_method_provider'
            - '@marello_shipping.shipping_price.provider'
        tags:
            - { name: oro_workflow.condition, alias: 'marello_has_applicable_shipping_methods' }
            - { name: oro_action.condition, alias: 'marello_has_applicable_shipping_methods' }

    marello_shipping.condition.shipping_method_has_shipping_rules:
        class: 'Marello\Bundle\ShippingBundle\Condition\ShippingMethodHasShippingRules'
        arguments:
            - '@marello_shipping.repository.shipping_methods_configs_rule'
        tags:
            - { name: oro_workflow.condition, alias: 'marello_shipping_method_has_shipping_rules' }
            - { name: oro_action.condition, alias: 'marello_shipping_method_has_shipping_rules' }

    marello_shipping.condition.shipping_method_has_enabled_shipping_rules:
        class: 'Marello\Bundle\ShippingBundle\Condition\ShippingMethodHasEnabledShippingRules'
        arguments:
            - '@marello_shipping.repository.shipping_methods_configs_rule'
        tags:
            - { name: oro_workflow.condition, alias: 'marello_shipping_method_has_enabled_shipping_rules' }
            - { name: oro_action.condition, alias: 'marello_shipping_method_has_enabled_shipping_rules' }

    marello_shipping.helper.filtered_datagrid_route:
        class: 'Marello\Bundle\ShippingBundle\Tools\FilteredDatagridRouteHelper'
        arguments:
                - '%marello_shipping.rule_grid_route_name%'
                - '%marello_shipping.rule_grid_name%'
                - '@oro_datagrid.helper.route'
