search:
    Marello\Bundle\RefundBundle\Entity\Refund:
        alias:                          marello_refund
        label:                          marello.refund.entity_plural_label
        route:
            name:                       marello_refund_view
            parameters:
                id:                     id
        search_template:                '@MarelloRefund/Refund/searchResult.html.twig'
        fields:
            -
                name:                   refundNumber
                target_type:            text
                target_fields:          [refundNumber]
            -
                name:                   order
                relation_type:          many-to-one
                relation_fields:
                    -
                        name:           orderNumber
                        target_type:    text
                        target_fields:  [orderNumber]
            -
                name:                   customer
                relation_type:          many-to-one
                relation_fields:
                    -
                        name:           email
                        target_type:    text
                        target_fields:  [email]
                    -
                        name:           firstName
                        target_type:    text
                        target_fields:  [firstName]
                    -
                        name:           lastName
                        target_type:    text
                        target_fields:  [lastName]