system_configuration:
    groups:
        notification_refund:
            title: marello.notification.system_configuration.groups.notification_refund.label
            priority: 60

    fields:
        marello_refund.refund_credited_template:
            data_type: string
            type: 'Marello\Bundle\NotificationBundle\Form\Type\EmailTemplateSelectType'
            options:
                label: marello.notification.config.fields.refund.refund_credited_template.label
                required: false
                entityName: Marello\Bundle\RefundBundle\Entity\Refund
                placeholder: marello.notification.config.fields.email_template.placeholder

    tree:
        system_configuration:
            marello:
                children:
                    notification:
                        children:
                            notification_configuration:
                                children:
                                    notification_refund:
                                        children:
                                            - marello_refund.refund_credited_template
        organization_configuration:
            marello:
                children:
                    notification:
                        children:
                            notification_configuration:
                                children:
                                    notification_refund:
                                        children:
                                            - marello_refund.refund_credited_template
        saleschannel_configuration:
            marello:
                children:
                    notification:
                        children:
                            notification_configuration:
                                children:
                                    notification_refund:
                                        children:
                                            - marello_refund.refund_credited_template