workflows:
    marello_refund_workflow:
        entity: Marello\Bundle\RefundBundle\Entity\Refund
        entity_attribute: refund
        start_step: pending

        defaults:
            active: true

        steps:
            pending:
                allowed_transitions:
                    - approve
            approved:
                allowed_transitions:
                    - credit
            credited:
                allowed_transitions:
                    - complete
            completed:
                allowed_transitions: []

        transitions:
            approve:
                step_to: approved
                transition_definition: approve_definition
            credit:
                step_to: credited
                transition_definition: credit_definition
            complete:
                step_to: completed
                transition_definition: complete_definition

        transition_definitions:
            approve_definition: []
            credit_definition:
                actions:
                    - '@extendable':
                        events: [extendable_action.refund_credited]
            complete_definition:
                actions:
                    - '@marello_notification_send':
                        entity: $refund
                        recipient: $refund.order.customer
                        template: marello_refund_credited
