workflows:
    marello_refund_workflow:
        entity: Marello\Bundle\RefundBundle\Entity\Refund
        entity_attribute: refund
        start_step: pending

        defaults:
            active: true

        steps:
            pending:
                allowed_transitions:
                    - approve
            approved:
                allowed_transitions:
                    - credit
            credited:
                allowed_transitions:
                    - complete
            completed:
                allowed_transitions: []
        attributes:
            email_template_name:
                type: string
        transitions:
            approve:
                step_to: approved
                transition_definition: approve_definition
            credit:
                step_to: credited
                transition_definition: credit_definition
            complete:
                step_to: completed
                transition_definition: complete_definition

        transition_definitions:
            approve_definition:
                actions:
                    - '@foreach':
                        array: $refund.items
                        value: $.result.value
                        actions:
                            - '@call_service_method':
                                  service: Marello\Bundle\RefundBundle\Provider\RefundItemRemovalProvider
                                  method: removeFromRefund
                                  method_parameters: [$.result.value]
            credit_definition:
                actions:
                    - '@extendable':
                        events: [extendable_action.refund_credited]
            complete_definition:
                actions:
                    -   '@call_service_method':
                            service: oro_config.manager
                            method: get
                            method_parameters:
                                - 'marello_refund.refund_credited_template'
                                - false
                                - false
                                - $refund.order.salesChannel
                            attribute: $email_template_name
                    - '@marello_notification_send':
                        entity: $refund
                        recipient: $refund.order.customer
                        template: $email_template_name
