Marello\Bundle\CustomerBundle\Entity\Customer:
    constraints:
        - Marello\Bundle\CustomerBundle\Validator\Constraints\UniqueCustomerEmail: ~
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
              fields: [customerNumber, organization]
              message: 'marello.customer.customer.number.message'
    properties:
        firstName:
            - NotBlank: ~
        lastName:
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Email: ~

Marello\Bundle\CustomerBundle\Entity\Company:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [companyNumber, organization]
            message: 'marello.customer.company.number.message'
    properties:
        name:
            - NotBlank: ~
