datagrids:
    marello-tickets-grid:
        source:
            type: orm
            query:
                select:
                    - t
                    - CONCAT(tcust.firstName, ' ', tcust.lastName) as customer
                    - CONCAT(to.firstName, ' ', to.lastName) as owner
                    - CONCAT(ta.firstName, ' ', ta.lastName) as assigned_to
                    - tcat.name as category
                from:
                    - { table: Marello\Bundle\TicketBundle\Entity\Ticket, alias: t }
                join:
                    left:
                        - { join: t.customer, alias: tcust }
                        - { join: t.owner, alias: to }
                        - { join: t.assignedTo, alias: ta }
                        - { join: t.category, alias: tcat }
                groupBy: t.id, category, customer, owner, assigned_to
        columns:
            subject:
                label: marello.ticket.subject.label
            customer:
                label: marello.ticket.customer.label
                renderable: false
            name_prefix:
                label: marello.ticket.name_prefix.label
                renderable: false
            first_name:
                label: marello.ticket.first_name.label
            middle_name:
                label: marello.ticket.middle_name.label
                renderable: false
            last_name:
                label: marello.ticket.last_name.label
            name_suffix:
                label: marello.ticket.name_suffix.label
                renderable: false
            email:
                label: marello.ticket.email.label
                renderable: false
            phone:
                label: marello.ticket.phone.label
                renderable: false
            owner:
                label: marello.ticket.owner.label
            assigned_to:
                label: marello.ticket.assigned_to.label
            source:
                label: marello.ticket.ticket_source.label
                frontend_type: string
                data_name: ticketSource
                renderable: false
            priority:
                label: marello.ticket.ticket_priority.label
                frontend_type: string
                data_name: ticketPriority
            status:
                label: marello.ticket.ticket_status.label
                frontend_type: string
                data_name: ticketStatus
            category:
                label: marello.ticket.category.label
                renderable: false
            createdAt:
                label: oro.ui.created_at
                frontend_type: datetime
            updatedAt:
                label: oro.ui.updated_at
                frontend_type: datetime
        properties:
            id: ~
            update_link:
                type: url
                route: marello_ticket_ticket_update
                params:     [ id ]
            view_link:
                type: url
                route: marello_ticket_ticket_view
                params:     [ id ]
        actions:
            edit:
                type:           navigate
                label:          oro.grid.action.update
                icon:           edit
                link:           update_link
            view:
                type:           navigate
                label:          oro.grid.action.view
                link:           view_link
                icon:           eye
                rowAction:      true
        filters:
            columns:
                createdAt:
                    type: datetime
                    data_name: t.createdAt
                updatedAt:
                    type: datetime
                    data_name: t.updatedAt
        sorters:
            columns:
                status:
                    data_name: t.ticketStatus
                createdAt:
                    data_name: t.createdAt
                updatedAt:
                    data_name: t.updatedAt
            default:
                createdAt: 'DESC'

    marello-ticket-categories-grid:
        source:
            type: orm
            query:
                select:
                    - c.id
                    - c.name
                from:
                    - { table: Marello\Bundle\TicketBundle\Entity\TicketCategory, alias: c }
        columns:
            id:
                label: marello.ticket.category.id.label
            name:
                label: marello.ticket.category.name
        properties:
            id: ~
            update_link:
                type: url
                route: marello_ticket_category_update
                params: [ id ]
            view_link:
                type: url
                route: marello_ticket_category_view
                params: [ id ]
        actions:
            edit:
                type:           navigate
                label:          oro.grid.action.update
                icon:           edit
                link:           update_link
            view:
                type:           navigate
                label:          oro.grid.action.view
                link:           view_link
                icon:           eye
                rowAction:      true

    marello-ticket-category-select-grid:
        extends: marello-ticket-categories-grid
        properties:
            id: ~
        actions: ~

    marello-ticket-customer:
        extended_entity_name: Marello\Bundle\TicketBundle\Entity\Ticket
        source:
            type: orm
            query:
                select:
                    - t
                    - CONCAT(to.firstName, ' ', to.lastName) as owner
                    - CONCAT(ta.firstName, ' ', ta.lastName) as assigned_to
                from:
                    - { table: Marello\Bundle\TicketBundle\Entity\Ticket, alias: t }
                join:
                    left:
                        - { join: t.owner, alias: to }
                        - { join: t.assignedTo, alias: ta }
                where:
                    and:
                        - t.customer = :customer_id
            bind_parameters:
                customer_id: customerId
        columns:
            subject:
                label: marello.ticket.subject.label
            first_name:
                label: marello.ticket.first_name.label
            last_name:
                label: marello.ticket.last_name.label
            owner:
                label: marello.ticket.owner.label
            assigned_to:
                label: marello.ticket.assigned_to.label
            priority:
                label: marello.ticket.ticket_priority.label
                frontend_type: string
                data_name: ticketPriority
            status:
                label: marello.ticket.ticket_status.label
                frontend_type: string
                data_name: ticketStatus
        properties:
            view_link:
                type: url
                route: marello_ticket_ticket_view
                params: [ id ]
        actions:
            view:
                type:           navigate
                label:          oro.grid.action.view
                link:           view_link
                icon:           eye
                rowAction:      true
        options:
            toolbarOptions:
                hide: true
                pageSize:
                    items: [ 10 ]
                    default_per_page: 10

    marello-category-tickets-grid:
        extended_entity_name: Marello\Bundle\TicketBundle\Entity\Ticket
        source:
            type: orm
            query:
                select:
                    - t
                    - CONCAT(to.firstName, ' ', to.lastName) as owner
                    - CONCAT(ta.firstName, ' ', ta.lastName) as assigned_to
                from:
                    - { table: Marello\Bundle\TicketBundle\Entity\Ticket, alias: t }
                join:
                    left:
                        - { join: t.owner, alias: to }
                        - { join: t.assignedTo, alias: ta }
                where:
                    and:
                        - t.category = :category_id
            bind_parameters:
                category_id: categoryId
        columns:
            subject:
                label: marello.ticket.subject.label
            first_name:
                label: marello.ticket.first_name.label
            last_name:
                label: marello.ticket.last_name.label
            owner:
                label: marello.ticket.owner.label
            assigned_to:
                label: marello.ticket.assigned_to.label
            priority:
                label: marello.ticket.ticket_priority.label
                frontend_type: string
                data_name: ticketPriority
            status:
                label: marello.ticket.ticket_status.label
                frontend_type: string
                data_name: ticketStatus
        properties:
            view_link:
                type: url
                route: marello_ticket_ticket_view
                params: [ id ]
        actions:
            view:
                type:           navigate
                label:          oro.grid.action.view
                link:           view_link
                icon:           eye
                rowAction:      true
        options:
            toolbarOptions:
                hide: true
                pageSize:
                    items: [ 10 ]
                    default_per_page: 10