datagrids:
    marello-tickets-grid:
        source:
            type: orm
            query:
                select:
                    - t
                    - CONCAT(tcust.firstName, ' ', tcust.lastName) as customer
                    - CONCAT(to.firstName, ' ', to.lastName) as owner
                    - CONCAT(ta.firstName, ' ', ta.lastName) as assigned_to
                    - tcat.category as category
                from:
                    - { table: MarelloTicketBundle:Ticket, alias: t }
                join:
                    left:
                        - { join: t.customer, alias: tcust }
                        - { join: t.owner, alias: to }
                        - { join: t.assignedTo, alias: ta }
                        - { join: t.category, alias: tcat }
        columns:
            id:
                label: marello.ticket.id.label
            subject:
                label: marello.ticket.subject.label
            customer:
                label: marello.ticket.customer.label
            first_name:
                label: marello.ticket.first_name.label
            last_name:
                label: marello.ticket.last_name.label
            email:
                label: marello.ticket.email.label
            phone:
                label: marello.ticket.phone.label
            owner:
                label: marello.ticket.owner.label
            assigned_to:
                label: marello.ticket.assigned_to.label
            source:
                label: marello.ticket.source.label
                frontend_type: string
                data_name: ticketSource
            priority:
                label: marello.ticket.priority.label
                frontend_type: string
                data_name: ticketPriority
            category:
                label: marello.ticket.category.label
            description:
                label: marello.ticket.description.label
            resolution:
                label: marello.ticket.resolution.label
        properties:
            id: ~
            update_link:
                type: url
                route: marello_ticket_update
                params:
                    - id
        actions:
            edit:
                type: navigate
                label: Edit
                link: update_link
                icon: edit

    marello-ticket-categories-grid:
        source:
            type: orm
            query:
                select:
                    - c
                from:
                    - { table: MarelloTicketBundle:TicketCategory, alias: c }
        columns:
            id:
                label: marello.ticket.category.id.label
            category:
                label: marello.ticket.category.label
        properties:
            id: ~
            update_link:
                type: url
                route: marello_ticket_category_update
                params:
                    - id
        actions:
            edit:
                type: navigate
                label: Edit
                link: update_link
                icon: edit

    marello-ticket-category-select-grid:
        extends: marello-ticket-categories-grid
        properties:
            id: ~
        actions: ~