parameters:
services:
    marello_notification.email.send_processor:
        class: Marello\Bundle\NotificationBundle\Email\SendProcessor
        arguments:
            - @oro_notification.email_processor
            - @doctrine.orm.entity_manager
            - @oro_activity.manager
            - @oro_email.email_renderer

    marello_notification.workflow.send_notification_action:
        class: Marello\Bundle\NotificationBundle\Workflow\SendNotificationAction
        arguments:
            - @oro_workflow.context_accessor
            - @marello_notification.email.send_processor
        tags:
            - { name: oro_workflow.action, alias: marello_notification_send }

    marello_notification.provider.activity_list:
        class: Marello\Bundle\NotificationBundle\Provider\NotificationActivityListProvider
        arguments:
           - @oro_entity.doctrine_helper
           - @translator
           - @oro_entity_config.link.entity_manager
        tags:
           - { name: oro_activity_list.provider, priority: 80 }
