services:
    marello_notification.email.send_processor:
        class: Marello\Bundle\NotificationBundle\Email\SendProcessor
        arguments:
            - '@oro_notification.manager.email_notification'
            - '@doctrine.orm.entity_manager'
            - '@oro_activity.manager'
            - '@oro_email.email_renderer'
            - '@marello_locale.manager.email_template'
            - '@marello_notification.provider.entity_notification_configuration'

    marello_notification.workflow.send_notification_action:
        class: Marello\Bundle\NotificationBundle\Workflow\SendNotificationAction
        arguments:
            - '@oro_action.expression.context_accessor'
            - '@marello_notification.email.send_processor'
        tags:
            - { name: oro_action.action, alias: marello_notification_send }

    marello_notification.provider.activity_list:
        class: Marello\Bundle\NotificationBundle\Provider\NotificationActivityListProvider
        arguments:
           - '@oro_entity.doctrine_helper'
           - '@translator'
           - '@marello_notification.link.entity_manager'
           - '@oro_activity.association_helper'
        tags:
           - { name: oro_activity_list.provider, priority: 80 }

    marello_notification.link.entity_manager:
        tags:
            - { name: oro_service_link, service: doctrine.orm.entity_manager }

    marello_notification.provider.entity_notification_configuration:
        class: Marello\Bundle\NotificationBundle\Provider\EntityNotificationConfigurationProvider