api:
    entities:
        Marello\Bundle\ReturnBundle\Entity\ReturnEntity:
            documentation_resource: '@MarelloReturnBundle/Resources/doc/api/return.md'
            fields:
                createdAt:
                    exclude: true
                updatedAt:
                    exclude: true
            filters:
                exclusion_policy: all
                fields:
                    createdAt:
                        exclude: true
                    updatedAt:
                        exclude: true
            actions:
                create:
                    fields:
                        returnNumber:
                            exclude: true
                        salesChannelName:
                            exclude: true
                        locale:
                            exclude: true
                        localization:
                            exclude: true
                update: false
                delete: false
                delete_list: false
                get_relationship: false
                add_relationship: false
                update_relationship: false
                delete_relationship: false

        Marello\Bundle\ReturnBundle\Entity\ReturnItem:
            documentation_resource: '@MarelloReturnBundle/Resources/doc/api/return_item.md'
            fields:
                orderitem:
                    property_path: orderItem
                createdAt:
                    exclude: true
                updatedAt:
                    exclude: true
            filters:
                exclusion_policy: all
            actions:
                create:
                    fields:
                        status:
                            exclude: true
                update: false
                delete: false
                delete_list: false
                get_relationship: false
                add_relationship: false
                update_relationship: false
                delete_relationship: false
                get_subresource: false
