search:
    Marello\Bundle\ReturnBundle\Entity\ReturnEntity:
        alias:                          marello_return
        label:                          marello.return.returnentity.entity_plural_label
        route:
            name:                       marello_return_return_view
            parameters:
                id:                     id
        search_template:                '@MarelloReturn/Return/searchResult.html.twig'
        fields:
            -
                name:                   returnNumber
                target_type:            text
                target_fields:          [returnNumber]
            -
                name:                   order
                relation_type:          many-to-one
                relation_fields:
                    -
                        name:           orderNumber
                        target_type:    text
                        target_fields:  [orderNumber]
