system_configuration:
    groups:
        return:
            title: marello.return.system_configuration.groups.return.title
        return_configuration:
            title: marello.return.system_configuration.groups.return_configuration.title
            icon: fa-undo
            priority: 50

        ror_settings:
            title: marello.return.system_configuration.groups.ror_settings.title
            icon: fa-info
            priority: 100

        warranty_settings:
            title: marello.return.system_configuration.groups.warranty_settings.title
            icon: fa-info
            priority: 50

        notification_return:
            title: marello.notification.system_configuration.groups.notification_return.label
            priority: 70

    fields:
        marello_return.ror_period:
            type: Symfony\Component\Form\Extension\Core\Type\TextType
            data_type: integer
            priority: 120
            options:
                label: marello.return.system_configuration.fields.ror_period
                resettable: true
                required: true
                constraints:
                    - NotNull: ~
                    - Range:
                        min: 1

        marello_return.warranty_period:
            type: Symfony\Component\Form\Extension\Core\Type\TextType
            data_type: integer
            priority: 120
            options:
                label: marello.return.system_configuration.fields.warranty_period
                resettable: true
                required: true
                constraints:
                    - NotNull: ~
                    - Range:
                        min: 1

        marello_return.created_template:
            data_type: string
            type: 'Marello\Bundle\NotificationBundle\Form\Type\EmailTemplateSelectType'
            options:
                label: marello.notification.config.fields.return.return_created_template.label
                required: false
                entityName: Marello\Bundle\ReturnBundle\Entity\ReturnEntity
                placeholder: marello.notification.config.fields.email_template.placeholder

        marello_return.not_verified_template:
            data_type: string
            type: 'Marello\Bundle\NotificationBundle\Form\Type\EmailTemplateSelectType'
            options:
                label: marello.notification.config.fields.return.return_not_verified.label
                required: false
                entityName: Marello\Bundle\ReturnBundle\Entity\ReturnEntity
                placeholder: marello.notification.config.fields.email_template.placeholder

        marello_return.received_template:
            data_type: string
            type: 'Marello\Bundle\NotificationBundle\Form\Type\EmailTemplateSelectType'
            options:
                label: marello.notification.config.fields.return.return_received.label
                required: false
                entityName: Marello\Bundle\ReturnBundle\Entity\ReturnEntity
                placeholder: marello.notification.config.fields.email_template.placeholder

        marello_return.inspection_not_ok_template:
            data_type: string
            type: 'Marello\Bundle\NotificationBundle\Form\Type\EmailTemplateSelectType'
            options:
                label: marello.notification.config.fields.return.inspection_not_ok_template.label
                required: false
                entityName: Marello\Bundle\ReturnBundle\Entity\ReturnEntity
                placeholder: marello.notification.config.fields.email_template.placeholder

        marello_return.reminder_template:
            data_type: string
            type: 'Marello\Bundle\NotificationBundle\Form\Type\EmailTemplateSelectType'
            options:
                label: marello.notification.config.fields.return.reminder_template.label
                required: true
                constraints:
                    - NotNull: ~
                entityName: Marello\Bundle\ReturnBundle\Entity\ReturnEntity

    tree:
        system_configuration:
            marello:
                children:
                    return:
                        children:
                            return_configuration:
                                children:
                                    ror_settings:
                                        children:
                                            - marello_return.ror_period
                                    warranty_settings:
                                        children:
                                            - marello_return.warranty_period
                    notification:
                        children:
                            notification_configuration:
                                children:
                                    notification_return:
                                        children:
                                            - marello_return.created_template
                                            - marello_return.not_verified_template
                                            - marello_return.received_template
                                            - marello_return.inspection_not_ok_template
                                            - marello_return.reminder_template

        organization_configuration:
            marello:
                children:
                    return:
                        children:
                            return_configuration:
                                children:
                                    ror_settings:
                                        children:
                                            - marello_return.ror_period
                                    warranty_settings:
                                        children:
                                            - marello_return.warranty_period
                    notification:
                        children:
                            notification_configuration:
                                children:
                                    notification_return:
                                        children:
                                            - marello_return.created_template
                                            - marello_return.not_verified_template
                                            - marello_return.received_template
                                            - marello_return.inspection_not_ok_template
                                            - marello_return.reminder_template