dynamic-imports:
    marellosupplier:
        - marellosupplier/js/app/views/product-supplier-view
        - marellosupplier/js/app/views/product-suppliers-view
        - marellosupplier/js/app/components/supplier-component
