api:
    entity_aliases:
        Marello\Bundle\TaxBundle\Entity\TaxCode:
            alias: marellotaxcode
            plural_alias: marellotaxcodes

    entities:
        Marello\Bundle\TaxBundle\Entity\TaxCode:
            documentation_resource: '@MarelloTaxBundle/Resources/doc/api/taxcode.md'
            identifier_field_names: [code]
            fields:
                id:
                    exclude: true
                description:
                    exclude: true
                data:
                    exclude: true
                createdAt:
                    exclude: true
                updatedAt:
                    exclude: true
            filters:
                exclusion_policy: none
            actions:
                create: false
                update: false
                delete: false
                delete_list: false
                update_relationship: false
                delete_relationship: false