search:
    Marello\Bundle\TaxBundle\Entity\TaxCode:
        alias:                          marello_taxcodes
        route:
            name:                       marello_tax_taxcode_index
            parameters:
                id:                     id
        search_template: '@MarelloTax/TaxCode/searchResult.html.twig'
        fields:
            -
                name:                   code
                target_type:            text
                target_fields:          [code]

    Marello\Bundle\TaxBundle\Entity\TaxRate:
        alias:                          marello_taxrates
        route:
            name:                       marello_tax_taxrate_view
            parameters:
                id:                     id
        search_template:                '@MarelloTax/TaxRate/searchResult.html.twig'
        fields:
            -
                name:                   code
                target_type:            text
                target_fields:          [code]

    Marello\Bundle\TaxBundle\Entity\TaxJurisdiction:
        alias:                          marello_taxjurisdiction
        route:
            name:                       marello_tax_taxjurisdiction_view
            parameters:
                id:                     id
        search_template:                '@MarelloTax/TaxJurisdiction/searchResult.html.twig'
        fields:
            -
                name:                   code
                target_type:            text
                target_fields:          [code]
            -
                name:                   description
                target_type:            text
                target_fields:          [description]
