datagrids:
    marello-customer:
        source:
            type: orm
            query:
                select:
                    - c.id
                    - c
                from:
                    - { table: MarelloCustomerBundle:Customer, alias: c }
        columns:
            id:
                label: marello.customer.id.label
                renderable: false
            namePrefix:
                label: marello.customer.name_prefix.label
            firstName:
                label: marello.customer.first_name.label
            middleName:
                label: marello.customer.middle_name.label
            lastName:
                label: marello.customer.last_name.label
            nameSuffix:
                label: marello.customer.name_suffix.label
            email:
                label: marello.customer.email.label
            createdAt:
                label:            oro.ui.created_at
                frontend_type:    datetime
                renderable:       false
            updatedAt:
                label:            oro.ui.updated_at
                frontend_type:    datetime
                renderable:       false
        filters:
            columns:
                namePrefix:
                    type: string
                    data_name: c.namePrefix
                firstName:
                    type: string
                    data_name: c.firstName
                middleName:
                    type: string
                    data_name: c.middleName
                lastName:
                    type: string
                    data_name: c.lastName
                nameSuffix:
                    type: string
                    data_name: c.nameSuffix
                email:
                    type: string
                    data_name: c.email
                createdAt:
                    type: datetime
                    data_name: c.createdAt
                    enabled: false
                updatedAt:
                    type: datetime
                    data_name: c.updatedAt
                    enabled: false
        sorters:
            columns:
                namePrefix:
                    data_name: c.namePrefix
                firstName:
                    data_name: c.firstName
                middleName:
                    data_name: c.middleName
                lastName:
                    data_name: c.lastName
                nameSuffix:
                    data_name: c.nameSuffix
                email:
                    data_name: c.email
                createdAt:
                    data_name: c.createdAt
                updatedAt:
                    data_name: c.updatedAt
            default:
                createdAt: 'DESC'
        properties:
            view_link:
                type:   url
                route:  marello_customer_view
                params:
                    id: id
            update_link:
                type:   url
                route:  marello_customer_update
                params:
                    id: id
        actions:
            view:
                type:       navigate
                link:       view_link
                icon:       eye
                rowAction:  true
            update:
                type:       navigate
                link:       update_link
                icon:       edit
        options:
            entityHint: customer

    marello-customer-select-grid:
        extends: marello-customer
        properties:
            id: ~
        actions: ~

    marello-company-customers-select-grid:
        extends: marello-customer-select-grid
        source:
            query:
                select:
                    - company.name
                join:
                    left:
                        - { join: c.company, alias: company }
        columns:
            name:
                label: marello.customer.company.entity_label
        filters:
            columns:
                name:
                    type: string
                    data_name: company.name

    marello-companies-select-grid:
        extended_entity_name: 'Marello\Bundle\CustomerBundle\Entity\Company'
        acl_resource: marello_customer_company_view
        options:
            entityHint: marello.customer.company.entity_plural_label
        inline_editing:
            enable: true
            behaviour: enable_selected
            entity_name: 'Marello\Bundle\CustomerBundle\Entity\Company'
        source:
            type:         orm
            query:
                select:
                    - company.id
                    - company.name
                    - parent.name as parent_name
                from:
                    - { table: MarelloCustomerBundle:Company, alias: company }
                join:
                    left:
                        - { join: company.parent, alias: parent }
            hints:
                - HINT_TRANSLATABLE
        columns:
            id:
                label: marello.customer.company.id.label
                renderable: false
            name:
                label: marello.customer.company.name.label
            parent_name:
                label: marello.customer.company.parent.label
        properties:
            id: ~
        sorters:
            columns:
                name:
                    data_name: company.name
                parent_name:
                    data_name: parent_name
            default:
                name: 'ASC'
        filters:
            columns:
                name:
                    type:      string
                    data_name: company.name
                parent_name:
                    type:      string
                    data_name: parent.name

    marello-companies-grid:
        extends: marello-companies-select-grid
        source:
            query:
                select:
                    - company.createdAt
                    - company.companyNumber
                    - company.updatedAt
        options:
            entity_pagination: true
        columns:
            companyNumber:
                label:          marello.customer.company.company_number.label
                frontend_type:  string
            createdAt:
                label:          oro.ui.created_at
                frontend_type:  datetime
            updatedAt:
                label:          oro.ui.updated_at
                frontend_type:  datetime
        filters:
            columns:
                companyNumber:
                    type:  string
                    data_name:  company.companyNumber
                createdAt:
                    type: datetime
                    data_name: company.createdAt
                updatedAt:
                    type: datetime
                    data_name: company.updatedAt
        sorters:
            columns:
                companyNumber:
                    data_name: company.companyNumber
                createdAt:
                    data_name: company.createdAt
                updatedAt:
                    data_name: company.updatedAt

        properties:
            view_link:
                type:   url
                route:  marello_customer_company_view
                params: [ id ]
        actions:
            view:
                type:         navigate
                label:        oro.grid.action.view
                link:         view_link
                icon:         eye
                acl_resource: marello_customer_company
                rowAction:    true

    marello-company-customers-grid:
        extends: marello-customer
        source:
            query:
                where:
                    and:
                        - c.company IN (:company_and_children_ids)
            bind_parameters:
                company_and_children_ids:
                    default: 0
        properties:
            id: ~

    marello-company-customers-extend-grid:
        extends: marello-customer
        source:
            query:
                select:
                    - >
                        (
                            CASE WHEN (:company_id IS NOT NULL) THEN
                                CASE WHEN
                                    c MEMBER OF customerCompany.customers
                                    OR c.id IN (:data_in) AND c.id NOT IN (:data_not_in)
                                THEN true ELSE false END
                            ELSE
                                CASE WHEN c.id IN (:data_in) AND c.id NOT IN (:data_not_in)
                                THEN true ELSE false END
                            END
                        ) as belongsToCompany
                where:
                    or:
                        - c.company IS NULL
                        - c.company = :company_id
                join:
                    left:
                        -
                            join: 'Marello\Bundle\CustomerBundle\Entity\Company'
                            alias: customerCompany
                            conditionType: WITH
                            condition: 'customerCompany = :company_id'
            bind_parameters:
                -
                    name: company_id
                    default: null
                    type: integer
        columns:
            belongsToCompany:
                label:         marello.customer.company.label
                editable:      true
                frontend_type: boolean
                add_before:    true
        properties:
            id: ~
        actions: ~
        sorters:
            columns:
                belongsToCompany:
                    data_name: belongsToCompany
            default:
                belongsToCompany: 'DESC'
        filters:
            columns:
                belongsToCompany:
                    type:      boolean
                    data_name: belongsToCompany
        options:
            entityHint:        'Company customers'
            entity_pagination: true
            rowSelection:
                dataField: id
                columnName: belongsToCompany
                selectors:
                    included: '#appendCustomers'
                    excluded: '#removeCustomers'

    marello-customer-group:
        source:
            type: orm
            query:
                select:
                    - cg
                from:
                    - { table: MarelloCustomerBundle:CustomerGroup, alias: cg }
        columns:
            id:
                label: marello.customer_group.id.label
                renderable: false
            name:
                label: marello.customer_group.name.label
            createdAt:
                label: oro.ui.created_at
                frontend_type: datetime
            updatedAt:
                label: oro.ui.updated_at
                frontend_type: datetime
        filters:
            columns:
                name:
                    type: string
                    data_name: cg.name
                createdAt:
                    type: datetime
                    data_name: cg.createdAt
                updatedAt:
                    type: datetime
                    data_name: cg.updatedAt
        sorters:
            columns:
                name:
                    data_name: cg.name
                createdAt:
                    data_name: cg.createdAt
                updatedAt:
                    data_name: cg.updatedAt
            default:
                createdAt: 'DESC'
        properties:
            view_link:
                type: url
                route: marello_customer_group_view
                params:
                    id: id
            update_link:
                type: url
                route: marello_customer_group_update
                params:
                    id: id
        actions:
            view:
                type: navigate
                link: view_link
                icon: eye
                rowAction: true
            update:
                type: navigate
                link: update_link
                icon: edit

    marello-customer-group-customer:
        extends: marello-customer
        source:
            query:
                select:
                    - CONCAT(c.firstName, ' ', c.lastName) as fullName
                    - comp.name as companyName
                join:
                    left:
                        - { join: c.customerGroup, alias: customerGroup }
                        -   join: c.company
                            alias: comp
                where:
                    and:
                        - customerGroup.id = :customerGroupId
            bind_parameters:
                - customerGroupId
        columns:
            fullName:
                label: marello.customer.name.label
            companyName:
                label: marello.customer.company.label
            namePrefix:
                renderable: false
            firstName:
                renderable: false
            middleName:
                renderable: false
            lastName:
                renderable: false
            nameSuffix:
                renderable: false
            email:
                renderable: false
        sorters:
            columns:
                companyName:
                    data_name: companyName
            default:
                companyName: ASC
        filters:
            columns:
                fullName:
                    type: string
                    data_name: fullName
                companyName:
                    type: string
                    data_name: companyName
                namePrefix:
                    renderable: false
                firstName:
                    renderable: false
                middleName:
                    renderable: false
                lastName:
                    renderable: false
                nameSuffix:
                    renderable: false
                email:
                    renderable: false
                createdAt:
                    renderable: false
                updatedAt:
                    renderable: false

    marello-customer-group-customers-extend-grid:
        extends: marello-customer
        source:
            query:
                select:
                    - CONCAT(c.firstName, ' ', c.lastName) as fullName
                    - comp.name as companyName
                    - >
                        (
                            CASE WHEN (:customer_group_id IS NOT NULL) THEN
                                CASE WHEN
                                    c MEMBER OF customerGroup.customers
                                    OR c.id IN (:data_in) AND c.id NOT IN (:data_not_in)
                                THEN true ELSE false END
                            ELSE
                                CASE WHEN c.id IN (:data_in) AND c.id NOT IN (:data_not_in)
                                THEN true ELSE false END
                            END
                        ) as belongsToCustomerGroup
                where:
                    or:
                        - c.customerGroup IS NULL
                        - c.customerGroup = :customer_group_id
                join:
                    left:
                        -   join: 'Marello\Bundle\CustomerBundle\Entity\CustomerGroup'
                            alias: customerGroup
                            conditionType: WITH
                            condition: 'customerGroup = :customer_group_id'
                        - join: c.company
                          alias: comp
            bind_parameters:
                -   name: customer_group_id
                    default: null
                    type: integer
        columns:
            belongsToCustomerGroup:
                label: marello.customer_group.hasGroup.label
                editable: true
                frontend_type: boolean
                add_before: true
            fullName:
                label: marello.customer.name.label
            companyName:
                label: marello.customer.company.label
            namePrefix:
                renderable: false
            firstName:
                renderable: false
            middleName:
                renderable: false
            lastName:
                renderable: false
            nameSuffix:
                renderable: false
            email:
                renderable: false
        properties:
            id: ~
        actions: ~
        sorters:
            columns:
                belongsToCustomerGroup:
                    data_name: belongsToCustomerGroup
                companyName:
                    data_name: companyName
            default:
                belongsToCustomerGroup: 'DESC'
        filters:
            columns:
                belongsToCustomerGroup:
                    type: boolean
                    data_name: belongsToCustomerGroup
                fullName:
                    type: string
                    data_name: fullName
                companyName:
                    type: string
                    data_name: companyName
                namePrefix:
                    renderable: false
                firstName:
                    renderable: false
                middleName:
                    renderable: false
                lastName:
                    renderable: false
                nameSuffix:
                    renderable: false
                email:
                    renderable: false
                createdAt:
                    renderable: false
                updatedAt:
                    renderable: false
        options:
            entityHint: 'Customer group customers'
            entity_pagination: true
            rowSelection:
                dataField: id
                columnName: belongsToCustomerGroup
                selectors:
                    included: '#appendCustomers'
                    excluded: '#removeCustomers'

    marello-customer-group-select-grid:
        extended_entity_name: 'Marello\Bundle\CustomerBundle\Entity\CustomerGroup'
        acl_resource: marello_customer_group_view
        options:
            entityHint: marello.customer_group.entity_plural_label
        inline_editing:
            enable: true
            behaviour: enable_selected
            entity_name: 'Marello\Bundle\CustomerBundle\Entity\CustomerGroup'
        source:
            type: orm
            query:
                select:
                    - cg.id
                    - cg.name
                from:
                    - { table: MarelloCustomerBundle:CustomerGroup, alias: cg }
            hints:
                - HINT_TRANSLATABLE
        columns:
            id:
                label: marello.customer_group.id.label
                renderable: false
            name:
                label: marello.customer_group.name.label
        properties:
            id: ~
        sorters:
            columns:
                name:
                    data_name: cg.name
            default:
                name: 'ASC'
        filters:
            columns:
                name:
                    type: string
                    data_name: cg.name