navigation:
    menu_config:
        items:
            customers_tab:
                label: marello.customer.navigation.customers.label
                uri: '#'
                extras:
                    icon: fa-users
                    position: 40

            customers:
                label: marello.customer.entity_plural_label
                route: marello_customer_index
                extras:
                    routes: ['marello_customer_*']
                    position: 10

            companies:
                label: marello.customer.company.entity_plural_label
                route: marello_customer_company_index
                extras:
                    routes: ['marello_customer_company_*']
                    position: 5

            customer_groups:
                label: marello.customer_group.entity_plural_label
                route: marello_customer_group_index
                extras:
                    routes: [ 'marello_customer_group_*' ]
                    position: 4

            shortcut_new_company:
                label: 'marello.customer.company.menu.shortcut_new_company.label'
                route: 'marello_customer_company_create'
                extras:
                    description: 'marello.customer.company.menu.shortcut_new_company.description'
                    isCustomAction: true

            shortcut_list_companies:
                label: 'marello.customer.company.menu.shortcut_list_companies.label'
                route: 'marello_customer_company_index'
                extras:
                    description: 'marello.customer.company.menu.shortcut_list_companies.description'
                    isCustomAction: true

        tree:
            application_menu:
                children:
                    customers_tab:
                        children:
                            customers: ~
                            companies: ~
                            customer_groups: ~
            shortcuts:
                children:
                    shortcut_new_company: ~
                    shortcut_list_companies: ~

    titles:
        marello_customer_index: marello.customer.entity_plural_label
        marello_customer_view: 'Customer %name%'
        marello_customer_update: 'Customer %name% - Update'
        marello_customer_create: 'New Customer'
        marello_customer_company_index: marello.customer.company.entity_plural_label
        marello_customer_company_view: 'Company %companyName%'
        marello_customer_company_update: 'Company %companyName% - Update'
        marello_customer_company_create: 'New Company'
