search:
    Marello\Bundle\CustomerBundle\Entity\Customer:
        alias:                  marello_customer
        label:                  marello.customer.entity_plural_label
        route:
            name:               marello_customer_view
            parameters:
                id:             id
        search_template:        '@MarelloCustomer/Customer/searchResult.html.twig'
        fields:
            -   name: email
                target_type: text
                target_fields: [email]
            -
                name: customerNumber
                target_type: text
                target_fields: [customerNumber]
            -
                name: namePrefix
                target_type: text
                target_fields: [namePrefix]
            -
                name: firstName
                target_type: text
                target_fields: [firstName]
            -
                name: middleName
                target_type: text
                target_fields: [middleName]
            -
                name: lastName
                target_type: text
                target_fields: [lastName]
            -
                name: nameSuffix
                target_type: text
                target_fields: [nameSuffix]

    Marello\Bundle\CustomerBundle\Entity\Company:
        alias:                          marello_company
        label:                          marello.customer.company.entity_plural_label
        route:
            name:                       marello_customer_company_view
            parameters:
                id:                     id
        search_template:                '@MarelloCustomer/Company/searchResult.html.twig'
        fields:
            -
                name:                   name
                target_type:            text
                target_fields:          [name]

    Marello\Bundle\CustomerBundle\Entity\CustomerGroup:
        alias: marello_customer_group
        label: marello.customer_group.entity_plural_label
        route:
            name: marello_customer_group_view
            parameters:
                id: id
        search_template: '@MarelloCustomer/CustomerGroup/searchResult.html.twig'
        fields:
            -   name: name
                target_type: text
                target_fields: [ name ]