parameters:
    marello_order.entity.order.class: Marello\Bundle\OrderBundle\Entity\Order

services:
    marello_order.form.type.order:
        class: Marello\Bundle\OrderBundle\Form\Type\OrderType
        tags:
            - { name: form.type, alias: marello_order_order }

    marello_order.form.type.order_update:
        class: Marello\Bundle\OrderBundle\Form\Type\OrderUpdateType
        tags:
            - { name: form.type, alias: marello_order_update }

    marello_order.form.type.order_item:
        class: Marello\Bundle\OrderBundle\Form\Type\OrderItemType
        tags:
            - { name: form.type, alias: marello_order_item }

    marello_order.form.type.order_item_collection:
        class: Marello\Bundle\OrderBundle\Form\Type\OrderItemCollectionType
        tags:
            - { name: form.type, alias: marello_order_item_collection }

    marello_order.form.type.order_api:
        class: Marello\Bundle\OrderBundle\Form\Type\OrderApiType
        arguments:
            - @marello_order.form.data_transformer.sales_channel_to_id
        tags:
            - { name: form.type, alias: marello_order_api }

    marello_order.form.type.order_update_api:
        class: Marello\Bundle\OrderBundle\Form\Type\OrderApiUpdateType
        tags:
            - { name: form.type, alias: marello_order_update_api }

    marello_order.form.type.order_item_api:
        class: Marello\Bundle\OrderBundle\Form\Type\OrderItemApiType
        arguments:
            - @marello_order.form.data_transformer.product_to_sku
        tags:
            - { name: form.type, alias: marello_order_item_api }

    marello_order.form.order_api:
            class: Symfony\Component\Form\Form
            factory_method: createNamed
            factory_service: form.factory
            arguments:
                - ~
                - 'marello_order_api'

    marello_order.form.order_update_api:
            class: Symfony\Component\Form\Form
            factory_method: createNamed
            factory_service: form.factory
            arguments:
                - ~
                - 'marello_order_update_api'

    marello_order.form.handler.order_api:
        class: Marello\Bundle\OrderBundle\Form\Handler\OrderApiHandler
        scope: request
        arguments:
            - @marello_order.form.order_api
            - @marello_order.form.order_update_api
            - @request
            - @doctrine.orm.entity_manager

    marello_order.form.data_transformer.product_to_sku:
        class: Marello\Bundle\OrderBundle\Form\DataTransformer\ProductToSkuTransformer
        arguments:
            - @doctrine.orm.entity_manager

    marello_order.form.data_transformer.sales_channel_to_id:
        class: Oro\Bundle\FormBundle\Form\DataTransformer\EntityToIdTransformer
        arguments:
            - @doctrine.orm.entity_manager
            - MarelloSalesBundle:SalesChannel
