Marello\Bundle\AddressBundle\Entity\MarelloAddress:
    properties:
        street:
            - NotBlank: ~
        city:
            - NotBlank: ~
        postalCode:
            - NotBlank: ~
        country:
            - NotBlank: ~
        phone:
            - Length:
                max: 255

Marello\Bundle\OrderBundle\Entity\OrderItem:
    properties:
        product:
            - NotBlank: { groups: [api, Default] }
        price:
            - NotBlank: { groups: [api, Default] }
        tax:
            - NotBlank: { groups: [api, Default] }
        taxCode:
            - NotBlank: { groups: [api, Default] }
        rowTotalInclTax:
            - NotBlank: { groups: [api, Default] }
        rowTotalExclTax:
            - NotBlank: { groups: [api, Default] }
    constraints:
        - Marello\Bundle\OrderBundle\Validator\Constraints\AvailableInventory:
            fields: [quantity, order, product]
            errorPath: quantity

Marello\Bundle\OrderBundle\Entity\Order:
    properties:
        customer:
            - NotBlank: ~
        salesChannel:
            - NotBlank: ~
        billingAddress:
            - NotBlank:
                message: 'marello.order.address.validation.billing_not_blank'
        shippingAddress:
            - NotBlank:
                message: 'marello.order.address.validation.shipping_not_blank'
