services:
    marello_core.event_listener.refresh_context:
        class: 'Marello\Bundle\CoreBundle\EventListener\RefreshContextListener'
        decorates: oro_security.listener.refresh_context_listener
        parent: oro_security.listener.refresh_context_listener

    marello_core.event_listener.email_address_visibility:
        class: 'Marello\Bundle\CoreBundle\EventListener\EmailAddressVisibilityListener'
        arguments:
            - '@oro_email.email_address_visibility.manager'
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    Marello\Bundle\CoreBundle\EventListener\OrganizationCreateListener:
        arguments:
            - '@oro_distribution.handler.application_status'
            - '@Marello\Bundle\CoreBundle\Provider\SequenceNumberProvider'
        tags:
            - { name: doctrine.orm.entity_listener, entity: 'Oro\Bundle\OrganizationBundle\Entity\Organization', event: postPersist, priority: 255 }
