services:
    _defaults:
        tags:
            - { name: oro_message_queue.topic }

    Marello\Bundle\CoreBundle\Async\Topic\SequenceNumberEntityCreationTopic: ~
    Marello\Bundle\CoreBundle\Async\Topic\FileUpdateTopic: ~