system_configuration:
    groups:
        notification:
            title: marello.notification.system_configuration.groups.notification.title
        notification_configuration:
            title: marello.notification.system_configuration.groups.notification_configuration.title
            icon: fa-bell
        notification_general:
            title: marello.notification.system_configuration.groups.notification_general.label
