navigation:
    menu_config:
        items:
            marello_payments:
                label:           'marello.payment.entity_plural_label'
                route:           'marello_payment_index'
                extras:
                    routes:      ['marello_payment_*']
                    position:    45

            marello_payment_rules:
                label:           'marello.payment.menu.paymentmethodsconfigsrule.label'
                route:           'marello_payment_methods_configs_rule_index'
                position:        102
                extras:
                    routes:      ['/^marello_payment_methods_configs_rule/']
                    description: 'marello.payment.menu.paymentmethodsconfigsrule.description'

            shortcut_marello_payment_rules:
                label:           'marello.payment.menu.paymentmethodsconfigsrule.label'
                route:           'marello_payment_methods_configs_rule_index'
                extras:
                    description: 'marello.payment.menu.shortcut_paymentmethodsconfigsrule.description'

        tree:
            application_menu:
                children:
                    sales_tab:
                        children:
                            marello_payments: ~
                    system_tab:
                        children:
                            marello_payment_rules: ~
            shortcuts:
                children:
                    shortcut_marello_payment_rules: ~

    titles:
        marello_payment_index: 'marello.payment.entity_plural_label'
        marello_payment_methods_configs_rule_index: ~
        marello_payment_methods_configs_rule_view:  '%label%'
        marello_payment_methods_configs_rule_update: 'Payment Rule %id% - Edit'
        marello_payment_methods_configs_rule_create: 'Create Payment Rule'
