Marello\Bundle\WebhookBundle\Entity\Webhook:
    properties:
        name:
            - NotBlank: ~
        event:
            - NotBlank: ~
        secret:
            - NotBlank: ~
        callbackUrl:
            - NotBlank: ~
            - Url: ~
