acls:
    marello_supplier_create:
        type:       entity
        class:      Marello\Bundle\SupplierBundle\Entity\Supplier
        permission: CREATE

    marello_supplier_view:
        type:       entity
        class:      Marello\Bundle\SupplierBundle\Entity\Supplier
        permission: VIEW

    marello_supplier_update:
        type:       entity
        class:      Marello\Bundle\SupplierBundle\Entity\Supplier
        permission: EDIT

    marello_supplier_delete:
        type:       entity
        class:      Marello\Bundle\SupplierBundle\Entity\Supplier
        permission: DELETE
