acls:
    marello_category_create:
        type: entity
        class: Marello\Bundle\CatalogBundle\Entity\Category
        permission: CREATE

    marello_category_view:
        type: entity
        class: Marello\Bundle\CatalogBundle\Entity\Category
        permission: VIEW

    marello_category_update:
        type: entity
        class: Marello\Bundle\CatalogBundle\Entity\Category
        permission: EDIT