api:
    entities:
        Marello\Bundle\CatalogBundle\Entity\Category:
            fields:
                createdAt:
                    exclude: true
                updatedAt:
                    exclude: true
            filters:
                exclusion_policy: all
            actions:
                delete_relationship: false
