acls:
    marello_product_create:
        type: entity
        class: Marello\Bundle\ProductBundle\Entity\Product
        permission: CREATE

    marello_product_view:
        type: entity
        class: Marello\Bundle\ProductBundle\Entity\Product
        permission: VIEW

    marello_product_update:
        type: entity
        class: Marello\Bundle\ProductBundle\Entity\Product
        permission: EDIT

    marello_product_delete:
        type: entity
        class: Marello\Bundle\ProductBundle\Entity\Product
        permission: DELETE

    marello_product_create_variant:
        type: entity
        class: Marello\Bundle\ProductBundle\Entity\Variant
        permission: CREATE

    marello_product_add_variant:
        type: entity
        class: Marello\Bundle\ProductBundle\Entity\Variant
        permission: EDIT