api:
    entity_aliases:
        Marello\Bundle\ProductBundle\Entity\Product:
            alias: marelloproduct
            plural_alias: marelloproducts

        Marello\Bundle\ProductBundle\Entity\Variant:
            alias: marellovariant
            plural_alias: marellovariants

        Marello\Bundle\ProductBundle\Entity\ProductChannelTaxRelation:
            alias: marelloproductchanneltax
            plural_alias: marelloproductchanneltaxes

    entities:
        Marello\Bundle\ProductBundle\Entity\Product:
            documentation_resource: '@MarelloProductBundle/Resources/doc/api/product.md'
            identifier_field_names: [sku]
            fields:
                saleschannels:
                    property_path: channels
                taxcode:
                    property_path: taxCode
                productstatus:
                    property_path: status
                variants:
                    property_path: variant
                channelsCodes:
                    exclude: true
                categoriesCodes:
                    exclude: true
            filters:
                exclusion_policy: all
                fields:
                    sku:
                        data_type: string
                        allow_array: true
                        property_path: sku
                        description: 'Filter by sku'
                    saleschannels:
                        data_type: string
                        allow_array: true
                        property_path: channels.code
                        description: 'Filter products by SalesChannel'
                    createdAt:
                        data_type: datetime
                        property_path: createdAt
                        description: 'Filter products by created at'
                    updatedAt:
                        data_type: datetime
                        property_path: updatedAt
                        description: 'Filter products by updated at'
            actions:
                #removed tags from API response as it cannot deal with SKU as identifier
                get:
                    fields:
                        tags:
                            exclude: true
                get_list:
                    fields:
                        tags:
                            exclude: true
                create:
                    fields:
                        prices:
                            exclude: true
                        channelPrices:
                            exclude: true

        Marello\Bundle\ProductBundle\Entity\Variant:
            documentation_resource: '@MarelloProductBundle/Resources/doc/api/variant.md'
            identifier_field_names: [variantCode]
            fields:
                products:
                    property_path: products
            filters:
                exclusion_policy: all
                fields:
                    variantCode:
                        data_type: string
                        allow_array: true
                        property_path: variantCode
                        description: 'Filter by variantCode'
                    createdAt:
                        data_type: datetime
                        property_path: createdAt
                        description: 'Filter variants by created at'
                    updatedAt:
                        data_type: datetime
                        property_path: updatedAt
                        description: 'Filter variants by updated at'
            actions:
                create: false
                delete: false
                delete_list: false
                add_relationship: false
                update_relationship: false
                delete_relationship: false

        Marello\Bundle\ProductBundle\Entity\ProductChannelTaxRelation:
            fields:
                taxcode:
                    property_path: taxCode
            filters:
                exclusion_policy: all
                fields:
                    sku:
                        data_type: string
                        allow_array: true
                        property_path: product.sku
                        description: 'Filter taxes by sku'
                    saleschannel:
                        data_type: string
                        allow_array: true
                        property_path: salesChannel.code
                        description: 'Filter taxes by SalesChannel'
                    taxcode:
                        data_type: string
                        allow_array: true
                        property_path: taxCode.code
                        description: 'Filter taxes by Taxcode'
                    createdAt:
                        data_type: datetime
                        property_path: createdAt
                        description: 'Filter taxes by created at'
                    updatedAt:
                        data_type: datetime
                        property_path: updatedAt
                        description: 'Filter taxes by updated at'
            actions:
                create: false
                delete: false
                delete_list: false
                add_relationship: false
                update_relationship: false
                delete_relationship: false