search:
    Marello\Bundle\ProductBundle\Entity\Product:
        alias: marello_product
        label: marello.product.entity_plural_label
        route:
            name: marello_product_view
            parameters:
                id: id
        search_template: '@MarelloProduct/Product/searchResult.html.twig'
        fields:
            -
                name: denormalizedDefaultName
                target_type: text
                target_fields: [denormalizedDefaultName]
            -
                name: names
                relation_type: many-to-many
                relation_fields:
                    -
                        name: string
                        target_type: text
                        target_fields: [names]
            -
                name: sku
                target_type: text
                target_fields: [sku]
            -
                name: manufacturingCode
                target_type: text
                target_fields: [manufacturingCode]