system_configuration:
    groups:
        product:
            title: marello.product.system_configuration.groups.product.title
        product_configuration:
            title: marello.product.system_configuration.groups.product_configuration.title
            icon: 'fa-barcode'
            priority: 100
        product_general:
            title: marello.product.system_configuration.groups.product_general.label
        related_items:
            title: marello.product.system_configuration.groups.related_items.title
            icon: 'fa-cog'
            priority: 110
        related_products:
            title: marello.product.system_configuration.groups.related_products.label
        upsell_products:
            title: marello.product.system_configuration.groups.upsell_products.label
        crosssell_products:
            title: marello.product.system_configuration.groups.crosssell_products.label

    fields:
        marello_product.use_external_url:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            options:
                label: marello.product.system_configuration.fields.use_external_url.label
                tooltip: marello.product.system_configuration.fields.use_external_url.tooltip
                required: false

        marello_product.related_products_bidirectional:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            priority: 90
            options:
                label: marello.product.system_configuration.fields.related_products_bidirectional.label
                tooltip: marello.product.system_configuration.fields.related_products_bidirectional.tooltip

        marello_product.max_number_of_related_products:
            data_type: integer
            type: Marello\Bundle\ProductBundle\Form\Type\ConfigIntegerType
            search_type: text
            priority: 80
            options:
                label: marello.product.system_configuration.fields.max_number_of_related_products.label
                tooltip: marello.product.system_configuration.fields.max_number_of_related_products.tooltip
                required: true
                constraints:
                    - NotBlank: ~
                    - Range:
                          min: 1

        marello_product.max_number_of_upsell_products:
            data_type: integer
            type: Marello\Bundle\ProductBundle\Form\Type\ConfigIntegerType
            search_type: text
            priority: 80
            options:
                label: marello.product.system_configuration.fields.max_number_of_upsell_products.label
                tooltip: marello.product.system_configuration.fields.max_number_of_upsell_products.tooltip
                required: true
                constraints:
                    - NotBlank: ~
                    - Range:
                          min: 1

        marello_product.max_number_of_crosssell_products:
            data_type: integer
            type: Marello\Bundle\ProductBundle\Form\Type\ConfigIntegerType
            search_type: text
            priority: 80
            options:
                label: marello.product.system_configuration.fields.max_number_of_crosssell_products.label
                tooltip: marello.product.system_configuration.fields.max_number_of_crosssell_products.tooltip
                required: true
                constraints:
                    - NotBlank: ~
                    - Range:
                          min: 1

    tree:
        system_configuration:
            marello:
                children:
                    product:
                        children:
                            product_configuration:
                                children:
                                    product_general:
                                        children:
                                            - marello_product.use_external_url
                            related_items:
                                children:
                                    related_products:
                                        children:
                                            - marello_product.related_products_bidirectional
                                            - marello_product.max_number_of_related_products
                                    upsell_products:
                                        children:
                                            - marello_product.max_number_of_upsell_products
                                            - marello_product.max_number_of_upsell_products
                                    crosssell_products:
                                        children:
                                            - marello_product.max_number_of_crosssell_products
                                            - marello_product.max_number_of_crosssell_products