services:
    Marello\Bundle\LocaleBundle\Api\Processor\ApiLocaleFilter:
        tags:
            - { name: oro.api.processor, action: get, group: build_query, priority: -160 , class: Marello\Bundle\SalesBundle\Entity\SalesChannel}
            - { name: oro.api.processor, action: get, group: build_query, priority: -160 , class: Marello\Bundle\FrontendBundle\Entity\FrontendMenu}
            - { name: oro.api.processor, action: get_list, group: build_query, priority: -160, class: Marello\Bundle\SalesBundle\Entity\SalesChannel}
            - { name: oro.api.processor, action: get_list, group: build_query, priority: -160, class: Marello\Bundle\FrontendBundle\Entity\FrontendMenu}
