oro_menu_config:
    items:
        returns:
            label: marello.return.returnentity.entity_plural_label
            route: marello_return_return_index
            extras:
                routes: ['marello_return_return_*']
    tree:
        application_menu:
            children:
                sales:
                    children:
                        returns: ~
                    position: 40

oro_titles:
    marello_return_return_index: marello.return.returnentity.entity_plural_label
    marello_return_return_view: 'Return #%%id%%'
    marello_return_return_create: 'New return'
