services:
    Marello\Bundle\ProductBundle\ImportExport\DataConverter\ProductDataConverter:
        parent: oro_importexport.data_converter.configurable
        calls:
          - [setFieldHelper, ['@oro_entity.helper.field_helper']]
          - [setEntityManager, ['@doctrine.orm.entity_manager']]
          - [setProductAttributesHelper, ['@Marello\Bundle\ProductBundle\ImportExport\Helper\ProductAttributesHelper']]
          - [setTranslator, ['@translator']]

    Marello\Bundle\ProductBundle\ImportExport\DataConverter\AssembledPriceListDataConverter:
        parent: oro_importexport.data_converter.configurable

    Marello\Bundle\ProductBundle\ImportExport\DataConverter\AssembledChannelPriceListDataConverter:
        parent: oro_importexport.data_converter.configurable

    Marello\Bundle\ProductBundle\ImportExport\EventListener\ProductImportExportSubscriber:
        tags:
          - { name: kernel.event_subscriber }

    Marello\Bundle\ProductBundle\ImportExport\Strategy\ProductStrategy:
        parent: oro_locale.importexport.strategy.localized_fallback_value_aware
        calls:
          - [setMimeTypeChecker, ['@oro_attachment.tools.mime_type_checker']]

    Marello\Bundle\ProductBundle\ImportExport\Strategy\AssembledPriceListStrategy:
        parent: oro_importexport.strategy.configurable_add_or_replace

    Marello\Bundle\ProductBundle\ImportExport\Strategy\AssembledChannelPriceListStrategy:
        parent: oro_importexport.strategy.configurable_add_or_replace

    marello_product.importexport.processor.export:
        parent: oro_importexport.processor.export_abstract
        calls:
            - [setDataConverter, ['@Marello\Bundle\ProductBundle\ImportExport\DataConverter\ProductDataConverter']]
        tags:
            - name: oro_importexport.processor
              type: export
              entity: Marello\Bundle\ProductBundle\Entity\Product
              alias: marello_product
            - name: oro_importexport.processor
              type: export_template
              entity: Marello\Bundle\ProductBundle\Entity\Product
              alias: marello_product

    marello_product.importexport.processor.export_price:
        parent: oro_importexport.processor.export_abstract
        calls:
            - [setDataConverter, ['@Marello\Bundle\ProductBundle\ImportExport\DataConverter\AssembledPriceListDataConverter']]
        tags:
            - name: oro_importexport.processor
              type: export_template
              entity: Marello\Bundle\PricingBundle\Entity\AssembledPriceList
              alias: marello_product_price

    marello_product.importexport.processor.export_channel_price:
        parent: oro_importexport.processor.export_abstract
        calls:
            - [setDataConverter, ['@Marello\Bundle\ProductBundle\ImportExport\DataConverter\AssembledChannelPriceListDataConverter']]
        tags:
            - name: oro_importexport.processor
              type: export_template
              entity: Marello\Bundle\PricingBundle\Entity\AssembledChannelPriceList
              alias: marello_product_channel_price

    marello_product.importexport.processor.import:
        parent: oro_importexport.processor.import_abstract
        calls:
            - [setDataConverter, ['@Marello\Bundle\ProductBundle\ImportExport\DataConverter\ProductDataConverter']]
            - [setStrategy, ['@Marello\Bundle\ProductBundle\ImportExport\Strategy\ProductStrategy']]
        tags:
            - name: oro_importexport.processor
              type: import
              entity: Marello\Bundle\ProductBundle\Entity\Product
              alias: marello_product
            - name: oro_importexport.processor
              type: import_validation
              entity: Marello\Bundle\ProductBundle\Entity\Product
              alias: marello_product

    marello_product.importexport.processor.import_price:
        parent: oro_importexport.processor.import_abstract
        calls:
            - [setDataConverter, ['@Marello\Bundle\ProductBundle\ImportExport\DataConverter\AssembledPriceListDataConverter']]
            - [setStrategy, ['@Marello\Bundle\ProductBundle\ImportExport\Strategy\AssembledPriceListStrategy']]
        tags:
            - name: oro_importexport.processor
              type: import
              entity: Marello\Bundle\PricingBundle\Entity\AssembledPriceList
              alias: marello_product_price
            - name: oro_importexport.processor
              type: import_validation
              entity: Marello\Bundle\PricingBundle\Entity\AssembledPriceList
              alias: marello_product_price

    marello_product.importexport.processor.import_channel_price:
        parent: oro_importexport.processor.import_abstract
        calls:
            - [setDataConverter, ['@Marello\Bundle\ProductBundle\ImportExport\DataConverter\AssembledChannelPriceListDataConverter']]
            - [setStrategy, ['@Marello\Bundle\ProductBundle\ImportExport\Strategy\AssembledChannelPriceListStrategy']]
        tags:
            - name: oro_importexport.processor
              type: import
              entity: Marello\Bundle\PricingBundle\Entity\AssembledChannelPriceList
              alias: marello_product_channel_price
            - name: oro_importexport.processor
              type: import_validation
              entity: Marello\Bundle\PricingBundle\Entity\AssembledChannelPriceList
              alias: marello_product_channel_price

    Marello\Bundle\ProductBundle\ImportExport\TemplateFixture\AttributeFamilyFixture:
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: oro_importexport.template_fixture }

    Marello\Bundle\ProductBundle\ImportExport\TemplateFixture\ProductFixture:
        arguments:
            - '@oro_entity.helper.field_helper'
            - '@Marello\Bundle\ProductBundle\ImportExport\Helper\ProductAttributesHelper'
        tags:
            - { name: oro_importexport.template_fixture }

    Marello\Bundle\ProductBundle\ImportExport\TemplateFixture\AssembledPriceListFixture:
        tags:
            - { name: oro_importexport.template_fixture }

    Marello\Bundle\ProductBundle\ImportExport\TemplateFixture\AssembledChannelPriceListFixture:
        tags:
            - { name: oro_importexport.template_fixture }

    Marello\Bundle\ProductBundle\ImportExport\Configuration\ProductConfiguration:
        arguments:
          - '@translator'
        tags:
          - { name: oro_importexport.configuration, alias: oro_product_index }

    Marello\Bundle\ProductBundle\ImportExport\Configuration\AssembledPriceListConfiguration:
        arguments:
          - '@translator'
        tags:
          - { name: oro_importexport.configuration, alias: oro_product_index }

    Marello\Bundle\ProductBundle\ImportExport\Configuration\AssembledChannelPriceListConfiguration:
        arguments:
          - '@translator'
        tags:
          - { name: oro_importexport.configuration, alias: oro_product_index }

    Marello\Bundle\ProductBundle\ImportExport\Serializer\ProductNormalizer:
        parent: oro_importexport.serializer.configurable_entity_normalizer
        tags:
            - { name: oro_importexport.normalizer }

    Marello\Bundle\ProductBundle\ImportExport\Serializer\ProductImageNormalizer:
        arguments:
            - '@Oro\Bundle\AttachmentBundle\Manager\FileManager'
        tags:
            - { name: oro_importexport.normalizer, priority: 10 }

    Marello\Bundle\ProductBundle\ImportExport\Helper\ProductAttributesHelper:
        arguments:
            - '@Oro\Bundle\EntityConfigBundle\Manager\AttributeManager'
