Marello\Bundle\ProductBundle\Entity\Product:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: sku
            message: 'marello.product.messages.error.sku'
    properties:
        name:
            - NotBlank: ~
            - Length:
                max: 255
        sku:
            - NotBlank: ~
        prices:
            - NotBlank: ~
