Marello\Component\Pricing\Entity\ProductChannelPrice:
    constraints:
        - Marello\Component\Pricing\Validator\Constraints\UniqueEntityCollection:
            fields: [channel, currency]
            errorPath: channel
            message: 'marello.pricing.productchannelprice.messages.error.unique_channel_price'
    properties:
        channel:
            - NotBlank: ~
        currency:
            - NotBlank: ~
        value:
            - NotBlank: ~
