services:
    marello_manual_shipping.form.type.manual_shipping_options:
        class: 'Marello\Bundle\ManualShippingBundle\Form\Type\ManualShippingOptionsType'
        arguments:
            - '@Marello\Bundle\PricingBundle\Rounding\PriceRoundingService'
        tags:
            - { name: form.type }
