services:
    marello_extend_workflow.api.workflow_start.action_processor:
        class: 'Marello\Bundle\ExtendWorkflowBundle\Api\Processor\WorkflowActionProcessor'
        public: true
        arguments:
            - '@oro_api.processor_bag'
            - 'start_workflow'
            - '@oro_api.config_provider'
            - '@oro_api.metadata_provider'
        tags:
            - { name: marello.api.action.processor }

    marello_extend_workflow.api.workflow_transit.action_processor:
        class: 'Marello\Bundle\ExtendWorkflowBundle\Api\Processor\WorkflowActionProcessor'
        public: true
        arguments:
            - '@oro_api.processor_bag'
            - 'transit_workflow'
            - '@oro_api.config_provider'
            - '@oro_api.metadata_provider'
        tags:
            - { name: marello.api.action.processor }

    marello_extend_workflow.api.workflow_activate.action_processor:
        class: 'Marello\Bundle\ExtendWorkflowBundle\Api\Processor\WorkflowActionProcessor'
        public: true
        arguments:
            - '@oro_api.processor_bag'
            - 'activate_workflow'
            - '@oro_api.config_provider'
            - '@oro_api.metadata_provider'
        tags:
            - { name: marello.api.action.processor }

    marello_extend_workflow.api.workflow_deactivate.action_processor:
        class: 'Marello\Bundle\ExtendWorkflowBundle\Api\Processor\WorkflowActionProcessor'
        public: true
        arguments:
            - '@oro_api.processor_bag'
            - 'deactivate_workflow'
            - '@oro_api.config_provider'
            - '@oro_api.metadata_provider'
        tags:
            - { name: marello.api.action.processor }

    marello_extend_workflow.api.workflow_start:
        class: 'Marello\Bundle\ExtendWorkflowBundle\Api\Processor\ProcessWorkflowStart'
        arguments:
            - '@oro_workflow.manager'
            - '@oro_entity.doctrine_helper'
            - '@oro_workflow.serializer.data.serializer'
            - '@oro_action.provider.button_search_context'
            - '@translator.default'
        tags:
            - { name: oro.api.processor, action: start_workflow }

    marello_extend_workflow.api.workflow_transit:
        class: 'Marello\Bundle\ExtendWorkflowBundle\Api\Processor\ProcessWorkflowTransit'
        arguments:
            - '@oro_workflow.manager'
            - '@translator.default'
        tags:
            - { name: oro.api.processor, action: transit_workflow }

    marello_extend_workflow.api.workflow_activate:
        class: 'Marello\Bundle\ExtendWorkflowBundle\Api\Processor\ProcessWorkflowToggle'
        arguments:
            - '@oro_workflow.manager'
            - '@translator.default'
            - 'activate'
        tags:
            - { name: oro.api.processor, action: activate_workflow }

    marello_extend_workflow.api.workflow_deactivate:
        class: 'Marello\Bundle\ExtendWorkflowBundle\Api\Processor\ProcessWorkflowToggle'
        arguments:
            - '@oro_workflow.manager'
            - '@translator.default'
            - 'deactivate'
        tags:
            - { name: oro.api.processor, action: deactivate_workflow }

    marello_extend_workflow.api.complete_errors:
        class: 'Oro\Bundle\ApiBundle\Processor\Shared\CompleteErrors'
        arguments:
            - '@oro_api.error_completer_registry'
        tags:
            - { name: oro.api.processor, action: start_workflow, group: normalize_result, priority: -10 }
            - { name: oro.api.processor, action: transit_workflow, group: normalize_result, priority: -10 }
            - { name: oro.api.processor, action: activate_workflow, group: normalize_result, priority: -10 }
            - { name: oro.api.processor, action: deactivate_workflow, group: normalize_result, priority: -10 }

    marello_extend_workflow.api.normalize_errors:
        class: 'Oro\Bundle\ApiBundle\Processor\Shared\NormalizeErrors'
        arguments:
            - '@translator'
        tags:
            - { name: oro.api.processor, action: start_workflow, group: normalize_result, priority: -20 }
            - { name: oro.api.processor, action: transit_workflow, group: normalize_result, priority: -20 }
            - { name: oro.api.processor, action: activate_workflow, group: normalize_result, priority: -20 }
            - { name: oro.api.processor, action: deactivate_workflow, group: normalize_result, priority: -20 }

    marello_extend_workflow.api.process_errors:
        class: 'Oro\Bundle\ApiBundle\Processor\Shared\ProcessErrors'
        tags:
            - { name: oro.api.processor, action: start_workflow, group: normalize_result, priority: -190 }
            - { name: oro.api.processor, action: transit_workflow, group: normalize_result, priority: -190 }
            - { name: oro.api.processor, action: activate_workflow, group: normalize_result, priority: -190 }
            - { name: oro.api.processor, action: deactivate_workflow, group: normalize_result, priority: -190 }
