services:
    marello_rule.expression_language:
        class: 'Oro\Component\ExpressionLanguage\ExpressionLanguage'
        public: false

    marello_rule.expression_language.function_count:
        class: 'Marello\Bundle\RuleBundle\ExpressionLanguage\CountExpressionLanguageFunction'
        tags:
            - { name: oro_rule.expression_language.function }

    marello_rule.rule_filtration.service:
        class: 'Marello\Bundle\RuleBundle\RuleFiltration\BasicRuleFiltrationService'
        public: false

    marello_rule.rule_filtration.enabled_decorator:
        class: 'Marello\Bundle\RuleBundle\RuleFiltration\EnabledRuleFiltrationServiceDecorator'
        public: false
        decorates: marello_rule.rule_filtration.service
        arguments:
            - '@marello_rule.rule_filtration.enabled_decorator.inner'

    marello_rule.rule_filtration.expression_language_decorator:
        class: 'Marello\Bundle\RuleBundle\RuleFiltration\ExpressionLanguageRuleFiltrationServiceDecorator'
        public: false
        decorates: marello_rule.rule_filtration.service
        decoration_priority: 250
        arguments:
            - '@marello_rule.expression_language'
            - '@marello_rule.rule_filtration.expression_language_decorator.inner'
            - '@logger'

    marello_rule.rule_filtration.stop_processing_decorator:
        class: 'Marello\Bundle\RuleBundle\RuleFiltration\StopProcessingRuleFiltrationServiceDecorator'
        public: false
        decorates: marello_rule.rule_filtration.service
        arguments:
            - '@marello_rule.rule_filtration.stop_processing_decorator.inner'

    marello_rule.action.visibility_provider:
        class: 'Marello\Bundle\RuleBundle\Datagrid\RuleActionsVisibilityProvider'

    marello_rule.validator_constraints.expression_language_syntax_validator:
        class: 'Marello\Bundle\RuleBundle\Validator\Constraints\ExpressionLanguageSyntaxValidator'
        arguments:
            - '@marello_rule.expression_language'
        tags:
            - { name: validator.constraint_validator, alias: oro_rule.validator_constraints.expression_language_syntax_validator }
