imports:
    - { resource: controllers.yml }
    - { resource: eventlisteners.yml }
    - { resource: mq_topics.yml }
services:
    Marello\Bundle\NotificationMessageBundle\Cron\NotificationMessageCleanupCommand:
        arguments:
            - '@doctrine'
        tags:
            - { name: console.command }

    marello_notification_message.datagrid.action_permission_provider:
        class: Marello\Bundle\NotificationMessageBundle\Datagrid\ActionPermissionProvider
        public: true

    Marello\Bundle\NotificationMessageBundle\Datagrid\Extension\MassAction\ResolveMassAction:
        shared: false
        public: true
        tags:
            - { name: oro_datagrid.extension.mass_action.type, type: notificationmessage_resolve }

    Marello\Bundle\NotificationMessageBundle\Datagrid\Extension\MassAction\ResolveMassActionHandler:
        public: true
        arguments:
            - '@doctrine'
            - '@translator'

    Marello\Bundle\NotificationMessageBundle\Provider\NotificationMessageEntityNameProvider:
        public: false
        tags:
            - { name: oro_entity.name_provider, priority: 100 }

    marello_notification_message.autocomplete.group.search_handler:
        parent: oro_form.autocomplete.search_handler
        arguments:
            - 'Oro\Bundle\UserBundle\Entity\Group'
            - ["name"]
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: user_group, acl_resource: oro_user_group_view }

    Marello\Bundle\NotificationMessageBundle\Form\Type\NotificationMessageGroupConfigType:
        arguments:
            - '@doctrine'
        tags:
            - { name: form.type, alias: marello_notificationmessage_group_config }

    Marello\Bundle\NotificationMessageBundle\Entity\Repository\NotificationMessageRepository:
        parent: oro_entity.abstract_repository
        arguments:
            - 'Marello\Bundle\NotificationMessageBundle\Entity\NotificationMessage'
        calls:
            - ['setAclHelper', ['@oro_security.acl_helper']]
        tags:
            - { name: doctrine.repository_service }

    Marello\Bundle\NotificationMessageBundle\Factory\NotificationMessageFactory:
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@oro_config.manager'
            - '@translator'
        tags:
            - { name: doctrine.repository_service }

    Marello\Bundle\NotificationMessageBundle\Async\ProcessNotificationMessageProcessor:
        arguments:
            - '@logger'
            - '@oro_entity.doctrine_helper'
            - '@Marello\Bundle\NotificationMessageBundle\Factory\NotificationMessageFactory'
        tags:
            - { name: 'oro_message_queue.client.message_processor' }