services:
    marello_ticket_categories:
        parent: oro_form.autocomplete.search_handler
        arguments:
            - 'Marello\Bundle\TicketBundle\Entity\TicketCategory'
            - [ 'name' ]
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: marello_ticket_category, acl_resource: marello_category_view }

    Marello\Bundle\TicketBundle\EventListener\OnTicketCreateEventListener:
        arguments:
            - '@oro_entity.doctrine_helper'
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    Marello\Bundle\TicketBundle\Entity\Repository\TicketRepository:
        parent: oro_entity.abstract_repository
        arguments:
            - 'Marello\Bundle\TicketBundle\Entity\Ticket'
        calls:
            - [setAclHelper, [ '@oro_security.acl_helper' ] ]
            - [setDateFilterProcessor, ['@oro_dashboard.filter.date_filter_processor']]
        tags:
            - { name: doctrine.repository_service }

    marello.ticket.provider.dashboard_data_provider:
        class: Marello\Bundle\TicketBundle\Provider\DashboardDataProvider
        public: true
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@oro_security.acl_helper'