acls:
    marello_notificationmessage_view:
        type:       entity
        class:      Marello\Bundle\NotificationMessageBundle\Entity\NotificationMessage
        permission: VIEW
    marello_notificationmessage_update:
        type:       entity
        class:      Marello\Bundle\NotificationMessageBundle\Entity\NotificationMessage
        permission: EDIT
