datagrids:
    marello-notificationmessage-grid:
        extended_entity_name: Marello\Bundle\NotificationMessageBundle\Entity\NotificationMessage
        inline_editing:
            enable: true
            behaviour: enable_selected
        source:
            type: orm
            query:
                select:
                    - na.id
                    - at.name as alertTypeName
                    - IDENTITY(na.alertType) as alertType
                    - IDENTITY(na.resolved) as resolved
                    - IDENTITY(na.source) as source
                    - na
                from:
                    - { table: Marello\Bundle\NotificationMessageBundle\Entity\NotificationMessage, alias: na }
                join:
                    inner:
                        - { join: na.alertType, alias: at }
                groupBy: na.id, at.id
        columns:
            id:
                label:            marello.notificationmessage.id.label
            alertType:
                label:            marello.notificationmessage.alert_type.label
                type: twig
                frontend_type:    html
                template:         '@MarelloNotificationMessage/NotificationMessage/Datagrid/Property/alertType.html.twig'
            source:
                label:            marello.notificationmessage.source.label
                choices:          "@oro_entity_extend.enum_value_provider->getEnumChoicesByCode('marello_notificationmessage_source')"
                frontend_type:    select
            title:
                label:            marello.notificationmessage.title.label
                frontend_type:    string
            count:
                label:            marello.notificationmessage.count.label
                frontend_type:    string
            resolved:
                label:            marello.notificationmessage.resolved.label
                choices:          "@oro_entity_extend.enum_value_provider->getEnumChoicesByCode('marello_notificationmessage_resolved')"
                frontend_type:    select
            createdAt:
                label:            oro.ui.created_at
                frontend_type:    datetime
            updatedAt:
                label:            oro.ui.updated_at
                frontend_type:    datetime
        sorters:
            columns:
                id:
                    data_name: na.id
                alertType:
                    data_name: alertType
                count:
                    data_name: na.count
                resolved:
                    data_name: resolved
                createdAt:
                    data_name: na.createdAt
                updatedAt:
                    data_name: na.createdAt
            default:
                createdAt: 'DESC'
        filters:
            columns:
                alertType:
                    type: enum
                    data_name: alertType
                    enum_code: marello_notificationmessage_alerttype
                source:
                    type: enum
                    data_name: source
                    enum_code: marello_notificationmessage_source
                title:
                    type: string
                    data_name: na.title
                resolved:
                    type: enum
                    data_name: resolved
                    enum_code: marello_notificationmessage_resolved
                createdAt:
                    type: datetime
                    data_name: na.createdAt
                updatedAt:
                    type: datetime
                    data_name: na.updatedAt
        properties:
            id: ~
            view_link:
                type:   url
                route:  marello_notificationmessage_view
                params:
                    id: id
            resolve_link:
                type:   url
                route:  marello_notificationmessage_resolve
                params:
                    id: id
        actions:
            view:
                type:         navigate
                label:        oro.grid.action.view
                link:         view_link
                icon:         eye
                rowAction:    true
            resolve:
                type:         ajax
                label:        marello.notificationmessage.actions.resolve.label
                link:         resolve_link
                icon:         check
                acl_resource: marello_notificationmessage_update
                defaultMessages:
                    success: marello.notificationmessage.actions.resolve.success
        action_configuration: ['@marello_notification_message.datagrid.action_permission_provider', 'getNotificationMessageActionPermissions']
        mass_actions:
            resolve:
                type:         notificationmessage_resolve
                acl_resource: marello_notificationmessage_update
                label:        marello.notificationmessage.mass_actions.resolve.label
                icon:         check
                entity_name:  'Marello\Bundle\NotificationMessageBundle\Entity\NotificationMessage'
                data_identifier: na.id
                defaultMessages:
                    confirm_content: marello.notificationmessage.actions.resolve.content
                    confirm_ok: marello.notificationmessage.actions.resolve.ok
        options:
            mass_actions:
                delete:
                    enabled: false
